### ISSUE TITLE
Qpython not working

### ISSUE THREAD

**Issue by koeniig2** [instabot-py/instabot.py#754] opened 2017-09-21 15:04 UTC
when i start the script on my android.. it says "no module named request"... people say to install request manually, but i dont know how to install it.. anyone can help me out here?

**Comment by luisramirez-m** [comment] 2017-09-21 16:07
You need to install Requests, In QPython you have to enter the option of the QPYPI menu, then there are 2 tabs (Programs and QPypi), you have to enter in the tab with the name Qpypi, clicking an option that says "Install With Python's PYPI".

After this opens a new console, where you can run commands with pip, example to install Request, you have to enter `pip install requests`.

I hope and understand me, excuse my English.

**Comment by koeniig2** [comment] 2017-09-22 07:15
Thank you sir.. that is a good tutorial :-) works

**Comment by TehJokeR** [comment] 2017-09-27 12:21
@koeniig2 if the issue is solves please close the issue

**Closed** 2018-01-11 22:31 UTC
