### ISSUE TITLE
Instagram API is not available.

### ISSUE THREAD

**Issue by Spawn** [instabot-py/instabot.py#1187] opened 2018-04-14 15:40 UTC
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [x] Other

### Operating System? (include version)
Linux

## Python Version?
3

## Description

Type the description of your issue here.

```
Traceback (most recent call last):
  File "/home/bogdan/pycharm-2017.2.1/helpers/pydev/pydevd.py", line 1599, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/bogdan/pycharm-2017.2.1/helpers/pydev/pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/bogdan/pycharm-2017.2.1/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/bogdan/Projects/instabot/example.py", line 55, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/home/bogdan/Projects/instabot/src/instabot.py", line 231, in __init__
    self.login()
  File "/home/bogdan/Projects/instabot/src/instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/home/bogdan/Projects/instabot/src/userinfo.py", line 41, in get_user_id_by_login
    all_data = json.loads(info.text)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Due to last Instagram API changing, endpoint which you're using (`__a=1`) is not working. Any ideas?

**Comment by gferrer807** [comment] 2018-04-14 16:11
Same issue. I am running Windows though

**Comment by gferrer807** [comment] 2018-04-14 16:29
Found a solution on [#1177](https://github.com/instabot-py/instabot.py/issues/1177)

Hope that helps. Use this website to find user_id [https://www.otzberg.net/iguserid/](https://www.otzberg.net/iguserid/)

**Comment by ChipWolf** [comment] 2018-04-14 21:01
Duplicate of #1153

**Closed by ChipWolf** 2018-04-14 21:01 UTC
