### ISSUE TITLE
No longer unfollowing

### ISSUE THREAD

**Issue by nekc-s** [instabot-py/instabot.py#1188] opened 2018-04-14 22:01 UTC
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android

MAC

## Python Version?
2 / 3

2

## Description

After weeks of running the bot without any issues, it has randomly stopped unfollowing since yesterday and keeps repeating the line "Trying to unfollow #1:" but doesn't actually unfollow anyone.

( the terminal will show it like this: 
14.04.2018_23:48 Trying to unfollow #1:
14.04.2018_23:48 Getting user info : censored
14.04.2018_23:49 Trying to like media: 1757525270132963517
14.04.2018_23:49 Liked: 1757525270132963517. Like #410.
14.04.2018_23:50 Trying to unfollow #1:
14.04.2018_23:50 Getting user info : censored
14.04.2018_23:50 Trying to like media: 1757499549688813435
14.04.2018_23:50 Liked: 1757499549688813435. Like #411.
14.04.2018_23:51 Trying to unfollow #1:
14.04.2018_23:51 Getting user info : censored
14.04.2018_23:52 Trying to like media: 1757498790737350893
14.04.2018_23:52 Liked: 1757498790737350893. Like #412.
14.04.2018_23:52 Trying to unfollow #1:
14.04.2018_23:52 Getting user info : censored )

I am running the latest version of the bot in mode 0. 

everything else is working perfectly! is this due to the new API? or does anyone know how to fix this?

```
Include the contents of the error.log here (if applicable).
```

ERROR:root:Except on auto_unfollow!
Traceback (most recent call last):
  File "/Users/MacbookPro/Desktop/bot/src/instabot.py", line 847, in auto_unfollow
    all_data = json.loads(r.text)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by ChipWolf** [comment] 2018-04-15 09:45
Duplicate of #1153

**Closed by ChipWolf** 2018-04-15 09:45 UTC
