### ISSUE TITLE
"get_media" after the quick fix

### ISSUE THREAD

**Issue by uzico** [instabot-py/instabot.py#1057] opened 2018-03-17 12:30 UTC
Still having issues with "get_media" after the fix, any ideas?

Both, userinfo.py and user_info.py are already fixed by #1048 

```
17.03.2018_13:17======> Get media id by user: elrincondelsaiyajin <======
17.03.2018_13:17 XXXXXXX Except on get_media! XXXXXXX
@@@@@@@@@@@@@@ This is your follower B****h!!! @@@@@@@@@@@@@
17.03.2018_13:18 blablabla : Get media id on recent feed 
 17.03.2018 13:18
17.03.2018_13:18 Media in recent feed = 12
xxxxxxx user info list is empty!!! xxxxxxxxx
17.03.2018_13:18 blablabla : Get media id on recent feed 
 17.03.2018 13:18
17.03.2018_13:18 Media in recent feed = 12
17.03.2018_13:18 blablabla : Get user info 
17.03.2018 13:18
17.03.2018_13:18 Checking user info..
17.03.2018_13:18 Follower : 85
17.03.2018_13:18 Following : 96
17.03.2018_13:18 Media : 94
   >>>This is a normal account
   >>>This user is active
   >>>This account is following you
   >>>You are following this account
17.03.2018_13:18 ======> Get media id by user: elrincondelsaiyajin <======
17.03.2018_13:18 XXXXXXX Except on get_media! XXXXXXX
17.03.2018_13:20 blablabla : Get user info 
17.03.2018 13:20
17.03.2018_13:20 Checking user info..
17.03.2018_13:20 Follower : 85
17.03.2018_13:20 Following : 96
17.03.2018_13:20 Media : 94
   >>>This is a normal account
   >>>This user is active
   >>>This account is following you
   >>>You are following this account
17.03.2018_13:20 ======> Get media id by user: elrincondelsaiyajin <======
17.03.2018_13:20 XXXXXXX Except on get_media! XXXXXXX
17.03.2018_13:21 blablabla : Get user info 
17.03.2018 13:21
17.03.2018_13:21 Checking user info..
17.03.2018_13:21 Follower : 85
17.03.2018_13:21 Following : 96
17.03.2018_13:21 Media : 94
   >>>This is a normal account
   >>>This user is active
   >>>This account is following you
   >>>You are following this account
17.03.2018_13:21 ======> Get media id by user: elrincondelsaiyajin <======
17.03.2018_13:21 XXXXXXX Except on get_media! XXXXXXX
17.03.2018_13:22 blablabla : Get user info 
17.03.2018 13:22
17.03.2018_13:22 Checking user info..
17.03.2018_13:22 Follower : 85
17.03.2018_13:22 Following : 96
17.03.2018_13:22 Media : 94
   >>>This is a normal account
   >>>This user is active
   >>>This account is following you
   >>>You are following this account
17.03.2018_13:22 ======> Get media id by user: elrincondelsaiyajin <======
17.03.2018_13:22 XXXXXXX Except on get_media! XXXXXXX
```

**Comment by fsadock** [comment] 2018-03-17 15:54
I managed to make it work by changing the files 'user_feed.py' and 'likers_protocol.py'. Not sure if is the best fix though.
I only changed what is highlighted

**likers_protocol.py:**
![20180317155140489](https://user-images.githubusercontent.com/12645994/37557354-fcb9fc0c-29e1-11e8-9fff-0528cbf26378.png)

**user_feed.py:**
![20180317155114762](https://user-images.githubusercontent.com/12645994/37557355-fcdb497a-29e1-11e8-9b7c-393bc40b561e.png)

**Comment by uzico** [comment] 2018-03-17 16:05
Wow, that seems to work! Thank you!

**Comment by RhaegarTargaryen55** [comment] 2018-03-17 17:38
@fsadock thank you, looks like now everything works pretty well!
p.s. any idea why the bot almost instantly unfollowing recently followed accounts? i see it's following, 1-2 minutes and it's unfollowing. 

parameters 
follow_time=6 * 60 * 60,
unfollow_break_min=15,
unfollow_break_max=30,

**Comment by fsadock** [comment] 2018-03-17 18:24
@RhaegarTargaryen55 no idea, maybe it has to do with the 'mode' you're using[?].

**Comment by RhaegarTargaryen55** [comment] 2018-03-17 18:41
@fsadock to be honest i run it on default mode, not even sure what exactly is

**Comment by marcosenno88** [comment] 2018-03-19 08:09
I fixed with #1048 and the I fixed with this. But I still have issue with except on get_media. Someone can help me plz?

**Comment by Stepyon** [comment] 2018-03-19 23:08
I also have "except on get_media", it appears if I use other than "0" mode. And the bug is inside recent_feed.py. I guess the issue is in line "19":

self.media_on_feed = list(all_data['graphql']['user']['edge_web_feed_timeline']['edges'])

Anyone knows what's wrong here?

**Comment by Tidle999** [comment] 2018-03-20 14:42
same for me, bot only working with mode 0. all other modes does not work. if i am using a other account it is working again? WTF?

**Comment by marcovisibelli** [comment] 2018-03-28 09:07
This fix it recent_feed.py

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import datetime
import json
import time


def get_media_id_recent_feed(self):
    if self.login_status:
        now_time = datetime.datetime.now()
        log_string = "%s : Get media id on recent feed \n %s" % (
            self.user_login, now_time.strftime("%d.%m.%Y %H:%M"))
        self.write_log(log_string)
        url = 'https://www.instagram.com/'+str(self.user_login)+'/?__a=1'
        try:
            r = self.s.get(url)
            all_data = json.loads(r.text)
            print(all_data['graphql']['user']['edge_owner_to_timeline_media']['edges'])
            self.media_on_feed = list(all_data['graphql']['user']['edge_owner_to_timeline_media']['edges'])
            log_string = "Media in recent feed = %i" % (
                len(self.media_on_feed))
            self.write_log(log_string)
        except:
            self.media_on_feed = []
            self.write_log('Except on get media!!')
            time.sleep(20)
            return 0
    else:
        return 0

```

**Comment by ChipWolf** [comment] 2018-04-03 16:42
If this is still an issue, please open a new issue. Thanks!

**Closed by ChipWolf** 2018-04-03 16:42 UTC
