### ISSUE TITLE
Traceback (most recent call last):   File "example.py", line 52, in <module>     unfollow_whitelist=['example_user_1', 'example_user_2'])

### ISSUE THREAD

**Issue by sameer2012** [instabot-py/instabot.py#1232] opened 2018-04-23 04:27 UTC
23.04.2018_04:24 Instabot v1.2.0 started at 23.04.2018 04:24:

23.04.2018_04:24 Trying to login as rmgws...

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/root/Downloads/instagram bot/instabot.py-master/src/instabot.py", line 231, in __init__
    self.login()
  File "/root/Downloads/instagram bot/instabot.py-master/src/instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/root/Downloads/instagram bot/instabot.py-master/src/userinfo.py", line 41, in get_user_id_by_login
    all_data = json.loads(info.text)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by bodeezl** [comment] 2018-04-24 03:54
oh i have this same issue

**Comment by wizarduk** [comment] 2018-04-25 17:50
same issue

**Comment by ChipWolf** [comment] 2018-04-26 08:35
Duplicate of #1153

**Closed by ChipWolf** 2018-04-26 08:35 UTC
