### ISSUE TITLE
https://www.instagram.com/{username}/?__a=1 does not work any more

### ISSUE THREAD

**Issue by ziliangpeng** [instabot-py/instabot.py#1155] opened 2018-04-12 04:43 UTC
Instagram has banned getting data from https://www.instagram.com/{username}/?__a=1

![image](https://user-images.githubusercontent.com/551900/38656739-526cadea-3dd1-11e8-8714-7a9214c1956b.png)

You can still get the same json as before, it's hidden as a piece of javascript code inside `https://www.instagra.com/{username}`'s html code.

**Comment by ziliangpeng** [comment] 2018-04-12 04:44
That's why all your [Json Decoder](https://github.com/instabot-py/instabot.py/issues/1153) is having problems.

**Comment by emirbeytekin** [comment] 2018-04-12 06:46
:(

**Comment by tux1011** [comment] 2018-04-12 06:49
Check https://github.com/instabot-py/instabot.py/issues/1153  for a temp workaround.

**Comment by ChipWolf** [comment] 2018-04-12 08:30
Please do @ziliangpeng

**Comment by ChipWolf** [comment] 2018-04-12 08:31
It does seem to be working again though.

**Comment by ChipWolf** [comment] 2018-04-12 08:31
Duplicate of #1153

**Closed by ChipWolf** 2018-04-12 08:31 UTC

**Comment by ziliangpeng** [comment] 2018-04-12 08:33
@ChipWolf oh cool. the `__a=1` is working again.

**Comment by herwincamargo** [comment] 2018-04-13 00:59
@ChipWolf oh cool. the __a=1 is working again.

How to apply???

**Comment by gmp009** [comment] 2018-04-13 07:54
It work last day and now again down :/ Whats happening

**Comment by Powie** [comment] 2018-04-13 10:14
It seems that Instagram is making changes at the API's etc..... Also unfollow is broken again....

**Comment by instabot-master** [comment] 2018-04-13 22:12
my unfollow is also not working anymore

**Comment by gmp009** [comment] 2018-04-14 11:40
@salehmosleh  how to retrieve id of any profile do you have any URL for that ?

**Comment by gmp009** [comment] 2018-04-14 12:32
@salehmosleh IDK about PHP can you help me to code something like this in Java ?

**Comment by salehmosleh** [comment] 2018-04-14 12:47
I belive you have to use a server/host to run it , cuase instagram will change '__query_hash' every couple days. I you use this code on your app, you have to publish new version.
If you need java, read php codes and _GET vars and urls. To find a way for java.
Goodluck

**Comment by foolfeel** [comment] 2018-04-15 08:48
How you get instagram query hash?

**Comment by elmagekmosaad** [comment] 2018-05-01 15:43
the new url 
https://www.instagram.com/web/search/topsearch/?context=blended&query=" & username account here& "&rank_token=0.3953592318270893&count=1

**Comment by salehmosleh** [comment] 2018-05-02 10:54
@elmagekmosaad , it works, but just for searching. we need all posts of a user. thank you.

**Comment by salehmosleh** [comment] 2018-05-02 10:57
i found this project : [mgp25/Instagram-API](https://github.com/mgp25/Instagram-API) . it seems work fine, but without instagram login page.

**Comment by Mrp12** [comment] 2018-06-07 06:57
@salehmosleh your pasted php code cab be get how many user posts?

**Comment by salehmosleh** [comment] 2018-07-07 17:56
Hi gays and @Mrp12 , unfortunately my codes cannot get more posts, i mean you can get just first page of posts , not any more. Thank you.

**Comment by rvducay** [comment] 2018-11-26 03:57
> @gmp009 , yes , use this php codes to get first profile data and 12 posts :
> 
> ```
> $url = "https://www.instagram.com/".$username;
> $html = file_get_contents($url);
> $arr = explode('window._sharedData = ',$html);
> $arr = explode(';</script>',$arr[1]);
> $obj = json_decode($arr[0] , true);
> ```
> also you can use it in java codes. just read `https://www.instagram.com/username` url.
> you can find after(end_cursor) , id data into this codes.

This works! Thanks
