### ISSUE TITLE
Instabot problem! please help  JSONDecodeError

### ISSUE THREAD

**Issue by saidch1** [instabot-py/instabot.py#1165] opened 2018-04-13 07:00 UTC
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [X] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
Windows 10

## Python Version?
3

## Description

Type the description of your issue here.

Hello everyone; the instabot was working perfectly for the last few days. Today I had to restart my computer and when i tried to launch the instabot again, it woudn't work and gave me the following errors. How can I proceed?
Include the contents of the error.log here (if applicable).

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "C:\Users\Said\Downloads\instabot.py-master\src\instabot.py", line 231, in __init__
    self.login()
  File "C:\Users\Said\Downloads\instabot.py-master\src\instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "C:\Users\Said\Downloads\instabot.py-master\src\userinfo.py", line 41, in get_user_id_by_login
    all_data = json.loads(info.text)
  File "C:\Users\Said\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Said\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Said\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Kielkenny** [comment] 2018-04-13 07:02
Got the same since yesterday. Seems it gets a 403 error when loging in. :-/

**Comment by Tidle999** [comment] 2018-04-13 07:30
same error for me since yesterday.

**Comment by RCAHaertlein** [comment] 2018-04-13 07:32
Yup same issue.

**Comment by saidch1** [comment] 2018-04-13 07:59
hopefully, someone can help us with a solution?

**Comment by chrisoname** [comment] 2018-04-13 08:01
the JSON is coming back empty... I don't know why. Same issue since this morning.

**Comment by DigitalFriends** [comment] 2018-04-13 08:27
Same here

**Comment by ChipWolf** [comment] 2018-04-13 08:40
Duplicate of #1153

**Closed by ChipWolf** 2018-04-13 08:40 UTC
