### ISSUE TITLE
Receiving error when trying to log in

### ISSUE THREAD

**Issue by entorment** [instabot-py/instabot.py#907] opened 2018-01-15 18:24 UTC
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

### Operating System? (include version)
 Windows

## Python Version?
 3

## Description

When trying to log in, i receive this error. Not sure what im doing wrong at this point

```
15.01.2018_13:03 Trying to login as entorment...

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['', ''])
  File "C:\Users\Ouch\Downloads\instabot.py-master\src\instabot.py", line 227, in __init__
    self.login()
  File "C:\Users\Ouch\Downloads\instabot.py-master\src\instabot.py", line 296, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "C:\Users\Ouch\Downloads\instabot.py-master\src\userinfo.py", line 44, in get_user_id_by_login
    all_data = json.loads(info.text)
  File "C:\Users\Ouch\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Ouch\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Ouch\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by ugurozturk** [comment] 2018-01-15 21:47
remove the parameter of  unfollow_whitelist if dont using it

**Comment by entorment** [comment] 2018-01-15 22:00
So this unfollow_whitelist=['example_user_1', 'example_user_2'])

 into this? 

unfollow_whitelist=[''])

**Comment by ugurozturk** [comment] 2018-01-15 22:02
Just remove it.

**Comment by ugurozturk** [comment] 2018-01-15 22:03
To this.
```
# List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["this", "the", "your"],
                  ["photo", "picture", "pic", "shot", "snapshot"],
                  ["is", "looks", "feels", "is really"],
                  ["great", "super", "good", "very good", "good", "wow",
                   "WOW", "cool", "GREAT","magnificent", "magical",
                   "very cool", "stylish", "beautiful", "so beautiful",
                   "so stylish", "so professional", "lovely",
                   "so lovely", "very lovely", "glorious","so glorious",
                   "very glorious", "adorable", "excellent", "amazing"],
                  [".", "..", "...", "!", "!!", "!!!"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        'second', 'stuff', 'art', 'project', 'love', 'life', 'food', 'blog',
        'free', 'keren', 'photo', 'graphy', 'indo', 'travel', 'art', 'shop',
        'store', 'sex', 'toko', 'jual', 'online', 'murah', 'jam', 'kaos',
        'case', 'baju', 'fashion', 'corp', 'tas', 'butik', 'grosir', 'karpet',
        'sosis', 'salon', 'skin', 'care', 'cloth', 'tech', 'rental', 'kamera',
        'beauty', 'express', 'kredit', 'collection', 'impor', 'preloved',
        'follow', 'follower', 'gain', '.id', '_id', 'bags'
    ])
```

**Comment by entorment** [comment] 2018-01-15 22:11
I apologize for not knowing too much, recently started using python. 
When i put this

    unwanted_username_list=[
        'second', 'stuff', 'art', 'project', 'love', 'life', 'food', 'blog',
        'free', 'keren', 'photo', 'graphy', 'indo', 'travel', 'art', 'shop',
        'store', 'sex', 'toko', 'jual', 'online', 'murah', 'jam', 'kaos',
        'case', 'baju', 'fashion', 'corp', 'tas', 'butik', 'grosir', 'karpet',
        'sosis', 'salon', 'skin', 'care', 'cloth', 'tech', 'rental', 'kamera',
        'beauty', 'express', 'kredit', 'collection', 'impor', 'preloved',
        'follow', 'follower', 'gain', '.id', '_id', 'bags'
    ])
while True:


I receive this

C:\Users\Ouch\Downloads\instabot.py-master>python example.py
15.01.2018_17:10 Instabot v1.2.0 started at 15.01.2018 17:10:

15.01.2018_17:10 Trying to login as entorment...

Traceback (most recent call last):
  File "example.py", line 50, in <module>
    'follow', 'follower', 'gain', '.id', '_id', 'bags'
  File "C:\Users\Ouch\Downloads\instabot.py-master\src\instabot.py", line 227, in __init__
    self.login()
  File "C:\Users\Ouch\Downloads\instabot.py-master\src\instabot.py", line 296, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "C:\Users\Ouch\Downloads\instabot.py-master\src\userinfo.py", line 44, in get_user_id_by_login
    all_data = json.loads(info.text)
  File "C:\Users\Ouch\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Ouch\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Ouch\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by entorment** [comment] 2018-01-15 22:56
?

**Comment by ugurozturk** [comment] 2018-01-16 01:29
Please search or try more. Or send here full of your example.py.

**Comment by senatorlila** [comment] 2018-03-13 23:20
Having the same issue. Not sure why. Any solutions?

**Comment by herwincamargo** [comment] 2018-04-13 00:26
I'm having the same issue.

**Comment by ChipWolf** [comment] 2018-04-13 08:45
Duplicate of #1153

**Closed by ChipWolf** 2018-04-13 08:45 UTC
