### ISSUE TITLE
some technical issue

### ISSUE THREAD

**Issue by shrikantdange** [instabot-py/instabot.py#1172] opened 2018-04-13 18:25 UTC
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?
i have tried both didnt  do
#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other
some technical issue
### Operating System? (include version)
MAC / Windows / Linux / Android
Windows  system
## Python Version?
2 / 3
3.6
## Description
some technical issue
Type the description of your issue here.
when run in cmd didnt login just showed some random erroe
[error.txt](https://github.com/instabot-py/instabot.py/files/1908476/error.txt)
error code above
```
Include the contents of the error.log here (if applicable).
```
it was long code so i attached its text file, thank you

**Comment by WilliamCG1** [comment] 2018-04-13 18:28
Yeah I get that too on Windows....also Following.

**Comment by alexi26** [comment] 2018-04-13 19:45
Same Problem for me, Any solutions?

**Comment by dariusdev01** [comment] 2018-04-13 20:32
same problem here

**Comment by Danielmcm86** [comment] 2018-04-13 20:38
I'm having exactly the same issue on Termux on Android

**Comment by Kadabrah** [comment] 2018-04-13 21:53
API change from Instagram, hopefully an updated bot will be up soon. By changing its API, they are restricting access to Instagram for third party apps. This actually might be the end of bots since some fonctions wont be possible anymore.

**Comment by Instaerror** [comment] 2018-04-13 23:25
#1153 fixed

**Comment by Instaerror** [comment] 2018-04-14 11:46
https://github.com/Instaerror/instabot.py/commit/0e0032e2a3616abd411914bbd20718ecc1dffff5
https://github.com/instabot-py/instabot.py/pull/1183/commits/0e0032e2a3616abd411914bbd20718ecc1dffff5

**Comment by ChipWolf** [comment] 2018-04-14 20:58
Duplicate of #1153

**Closed by ChipWolf** 2018-04-14 20:58 UTC
