### ISSUE TITLE
Connection Failure 

### ISSUE THREAD

**Issue by jfinly** [instabot-py/instabot.py#1435] opened 2018-07-22 04:38 UTC
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
- [x] MAC
- [ ] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/util/connection.py", line 79, in create_connection
    raise err
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/util/connection.py", line 69, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connection.py", line 196, in connect
    conn = self._new_conn()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x1110e8128>: Failed to establish a new connection: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='ink361.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1110e8128>: Failed to establish a new connection: [Errno 60] Operation timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 47, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/JoshuaAlexander/Desktop/instabot.py-master/src/instabot.py", line 232, in __init__
    self.login()
  File "/Users/JoshuaAlexander/Desktop/instabot.py-master/src/instabot.py", line 300, in login
    ui = UserInfo()
  File "/Users/JoshuaAlexander/Desktop/instabot.py-master/src/userinfo.py", line 29, in __init__
    self.hello()
  File "/Users/JoshuaAlexander/Desktop/instabot.py-master/src/userinfo.py", line 34, in hello
    main = self.s.get(self.url_list[self.i_a]["main"])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='ink361.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1110e8128>: Failed to establish a new connection: [Errno 60] Operation timed out',))
```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
```

## Config

```
Include the contents of your config here (REMOVE YOUR USERNAME AND PASSWORD!) (if applicable). < REPLACE THIS TEXT
```

**Comment by LopesX** [comment] 2018-07-22 06:52
Same error

**Comment by adhavalboy** [comment] 2018-07-22 07:00
same error

**Comment by adhavalboy** [comment] 2018-07-22 07:01
This is due to ink361 going down. Just open userinfo.py file, find line 31 and change that function to return True:

def hello(self):
    self.s = requests.Session()
    self.s.headers.update({'User-Agent': self.user_agent})
    return True
It's NOT a real solution, though a quick and dirty fix that might help some of you guys until the problem is fixed. It solved the problem for me.

Alternatively, you can just grab my fork (make sure you go back to the original when it's patched):
https://github.com/canpoyrazoglu/instabot.py

**Comment by heldausberlin** [comment] 2018-07-22 08:11
Same here. The workaround of adhavalboy unfortunately doesn’t help.

**Comment by vineeth-pradhan** [comment] 2018-07-22 08:21
@adhavalboy Yes, that works temporarily
```
# src/userinfo.py
def hello(self):
    self.s = requests.Session()
    self.s.headers.update({'User-Agent': self.user_agent})
    # main = self.s.get(self.url_list[self.i_a]["main"])
    # if main.status_code == 200:
    #     return True
    return True
```

**Comment by d0minikt** [comment] 2018-07-22 08:35
Unfortunately, the workaround only allows me to log in, however, it later causes this error:
```
Traceback (most recent call last):
  File ".\example.py", line 96, in <module>
    feed_scanner(bot)
  File "C:\Users\domin\instabot.py\src\feed_scanner.py", line 55, in feed_scanner
    likers_graber_protocol(self)
  File "C:\Users\domin\instabot.py\src\likers_graber_protocol.py", line 27, in likers_graber_protocol
    likers_protocol(self)
  File "C:\Users\domin\instabot.py\src\likers_protocol.py", line 19, in likers_protocol
    current_index]["likes"]["count"] >= 10 and self.media_by_user[self.
KeyError: 'likes'
```

**Comment by Katsugi** [comment] 2018-07-22 09:06
Still getting this error after changing the userinfo.py file as suggested by @adhavalboy & @vineeth-pradhan :
Login error! Connection error!

**Comment by marcelcaferati** [comment] 2018-07-22 16:15
I didnt have to change anything, it just started working again this morning

**Comment by ugurozturk** [comment] 2018-07-23 12:08
> I didnt have to change anything, it just started working again this morning

So im closing it

**Closed by ugurozturk** 2018-07-23 12:08 UTC

**Comment by martgsi** [comment] 2018-09-23 12:49
same problem here
