### ISSUE TITLE
Could not find user in settings. Would you like to add now? (yes/no):

### ISSUE THREAD

**Issue by Brosno1** [instabot-py/instabot.py#2131] opened 2019-05-04 13:18 UTC
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [x] macOS
- [ ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
python --version 3.7
```

#### Pip Version?
```
pip --version 19
```

#### Description of your issue

```
After running through the instabot configurator (hence setting up my user info), it tells me to rerun the script to login. When I do, I enter my username and get the following:

'Could not find user in settings. Would you like to add now? (yes/no):' 

Sure I'm just being stupid and missing something but can't figure it out. Could anyone provide a solution or clear installation instructions.
```

#### Config

```

```

**Comment by Brosno1** [comment] 2019-05-04 13:18
Any help appreciated!

**Comment by waynoedm** [comment] 2019-05-10 10:30
It is looking for the username that you gave it when you first ran it. It has to be the same username you log in to instagram with. You may have a typo.  Open up your config file config.ini to see what username you saved to see if you typed it wrong.

**Comment by Okblyat** [comment] 2019-06-02 17:09
This is still an issue for me after checking the .ini conifg file and verifying the username. Also launched script as "python3 instabot_py USERNAME" and it still cannot locate the user. 

Any advice?

**Comment by f1she3** [comment] 2019-07-16 18:09
Hi !
I have the same issue here.
Steps to reproduce : 

- `python3 -m pip install instabot-py`

- run `instabot-py` for the first time, create a configuration file for your account, close

- rerun `instabot-py`, enter your username

==> Error : 

> Could not find user in settings. Would you like to add now?

I checked instabot.config.ini, it contains a section for my account with the right `username` and `password` values, and a [DEFAULT] section

My thought : My username contains capital letters and numbers, and my account contains ASCII caracters, such as |¬Ú¿bqÿn, so maybe there's a bug with either caps or ascii caracters

**Comment by Ananasee** [comment] 2019-07-21 19:14
It is because you have some non ASCII characters or symbols like "_ / ." in your account name!

I changed my account name to something with only letters, and now it function perfectly.

**Comment by f1she3** [comment] 2019-07-27 06:48
Thanks for your answer and sorry for the delay, in fact only my password contains non ASCII caracters, my account name only contains caps and numbers ...
So I think there's a BUG there

**Comment by canpoyrazoglu** [comment] 2019-09-25 20:39
I don't have non-ASCII characters on username/password though I'm still getting the same error. Any updates?

**Comment by nickgryg** [comment] 2019-12-27 19:08
This is very outdated issue. Please use instabot-py version 0.5.20 or later.

**Closed by nickgryg** 2019-12-27 19:08 UTC
