### ISSUE TITLE
Python failed to logging

### ISSUE THREAD

**Issue by MeM1011** [instabot-py/instabot.py#1231] opened 2018-04-22 23:05 UTC
While trying to logging example.py failed to logging as it seems that something just before "while true" is missing... We got this as an error

22.04.2018_22:57 Trying to login as blabla...

Traceback (most recent call last):
  File "example.py", line 50, in <module>
    'follow', 'follower', 'gain', '.id', '_id', 'bags' ])
  File "/home/pi/instabot.py/src/instabot.py", line 231, in __init__
    self.login()
  File "/home/pi/instabot.py/src/instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/home/pi/instabot.py/src/userinfo.py", line 41, in get_user_id_by_login
    all_data = json.loads(info.text)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by greenglass** [comment] 2018-04-23 15:57
#1218 fixed this issue for me

**Comment by bodeezl** [comment] 2018-04-24 03:59
#1218 fixed it for me too

**Comment by ChipWolf** [comment] 2018-04-26 08:35
Duplicate of #1153

**Closed by ChipWolf** 2018-04-26 08:35 UTC
