### ISSUE TITLE
Bot jumps from tag to tag after a like

### ISSUE THREAD

**Issue by remyx11** [instabot-py/instabot.py#1953] opened 2019-02-01 09:13 UTC
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [X] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [X] macOS
- [ ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [X] I am using Python 3.6 or above

#### Description of your issue

The bot is running fine, however it keeps switching from tag after each like, which takes some time in the long run. Is there any solution to this? I've found somewhere that changing "max_like_for_one_tag" to a higher value would work, but even if I set it to 100 it happens.

**Comment by dimisdas** [comment] 2019-02-01 09:14
Could you please post your config and which version/build you're using?

**Comment by remyx11** [comment] 2019-02-01 09:17
Yes, sorry. Version 1.2.1/0 and the config below;

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import time

from src import InstaBot
from src.check_status import check_status
from src.feed_scanner import feed_scanner
from src.follow_protocol import follow_protocol
from src.unfollow_protocol import unfollow_protocol

bot = InstaBot(
    login="",
    password="",
    start_at_h=9,
    start_at_m=10,
    end_at_h=20,
    end_at_m=10,
    like_per_day=500,
    comments_per_day=0,
    tag_list=['rumag', 'fujifilm', 'gh5', 'photography', 
    'filmmaker', 'film', 'fuji', 
    'travel', 'x100', 'landscapes'],
    tag_blacklist=['rain', 'thunderstorm'],
    user_blacklist={},
    max_like_for_one_tag=20,
    follow_per_day=0,
    follow_time=1 * 60,
    unfollow_per_day=0,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["this", "the", "your"],
                  ["photo", "picture", "pic", "shot", "snapshot"],
                  ["is", "looks", "feels", "is really"],
                  ["great", "super", "good", "very good", "good", "wow",
                   "WOW", "cool", "GREAT","magnificent", "magical",
                   "very cool", "stylish", "beautiful", "so beautiful",
                   "so stylish", "so professional", "lovely",
                   "so lovely", "very lovely", "glorious","so glorious",
                   "very glorious", "adorable", "excellent", "amazing"],
                  [".", "..", "...", "!", "!!", "!!!"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        'sex', 'sexy', 'nsfw', 'naked',
    ],
    unfollow_whitelist=['example_user_1', 'example_user_2'])
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 0

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)

    if mode == 0:
        bot.new_auto_mod()

    elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)

    elif mode == 2:
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3:
        bot.bot_mode = 3
        while(bot.login_status == 1):
            bot.unfollow_recent_feed()
            time.sleep(5)

    elif mode == 4:
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)

    else:
        print("Wrong mode!")

```

**Comment by dimisdas** [comment] 2019-02-01 09:33
I copied your config and it's working on my local build.

![screenshot 2019-02-01 at 11 27 45](https://user-images.githubusercontent.com/1391441/52114418-b175ce80-2614-11e9-8baf-e7f2de6e8731.jpg)

However, I see your example.py is using a bit of an older version than the current master. There hasn't been a new version release yet, and most changes have been minor. The config should have backwards compatibility anyway. 

But since I cannot reproduce this, could I burden you to pull the latest master and try configure it again?

**Comment by remyx11** [comment] 2019-02-01 09:35
Did you run it for a bit longer? Sometimes I have two likes per tag as well. Not more though..

I'm still learning a lot this, could you give me some intrusctions on how to pull the latest version? (It says there is an update i just noticed) Without losing my config.

**Comment by dimisdas** [comment] 2019-02-01 09:37
No worries. It kept liking, yeah.

You can either clone / pull using terminal and git, or download the .zip >
https://github.com/instabot-py/instabot.py/archive/master.zip

**Comment by remyx11** [comment] 2019-02-01 09:53
Kept it running for a bit, still the same.. It's odd that i just works at your computer and not mine, the new files should be the same.

![schermafbeelding 2019-02-01 om 10 52 30](https://user-images.githubusercontent.com/29894826/52115730-9d7b9e00-260f-11e9-91f6-b7dfa37f7d26.png)

**Comment by dimisdas** [comment] 2019-02-01 10:11
max_like_for_one_tag is a random number between 1 and n. The default is 5, but setting it to 50 should give variable results. I honestly can't figure it out. Will take another look later tonight.

**Comment by dimisdas** [comment] 2019-02-01 11:38
InstaPy has 21 dependencies, and InstaBot just 3, and the only common is Requests. It shouldn't matter.

I'm also on Mac. Will take a more thorough look and keep you posted.

**Comment by dimisdas** [comment] 2019-02-02 11:53
I managed to reproduce this yesterday night. I'm marking this as a bug.

**Comment by disprozzy** [comment] 2019-02-14 16:06
I have the same issue, another problem which appeared at the same time - bot does not comment the media it liked and switches to a new media for a comment

**Comment by husligc** [comment] 2019-05-24 16:16
> I managed to reproduce this yesterday night. I'm marking this as a bug.

Did this ever get fixed? Still a problem for me. Thanks

**Comment by itsmejamie** [comment] 2019-05-27 10:39
Been having this problem also, getting 1 like per tag. Have set the 'max_like_for_one_tag' to 10 and 'likes_per_day' at 1,000. I do also have nearly 100 tags. So maybe that is having an impact?

**Comment by Metacowboy** [comment] 2019-06-09 11:13
Same problem 1 like per tag, is this a setting problem or a bug?

**Comment by nickgryg** [comment] 2019-12-28 16:23
This is very outdated issue. If you still have issues, please use instabot-py version 0.5.20 or later.

**Closed by nickgryg** 2019-12-28 16:23 UTC
Labels: type/bug
