### ISSUE TITLE
The bot suddenly stopped to work last night

### ISSUE THREAD

**Issue by giovannaparadiso80** [instabot-py/instabot.py#1007] opened 2018-03-07 08:35 UTC
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC High Sierra 10.13.3

## Python Version?
3.6.4

## Description

Yesterday night I launched the bot as usual, and this happens: 
Traceback (most recent call last):
  File "/Users/giovannaparadiso/Desktop/Giovanna/INSTA-BOT/instabot.py-master/example.py", line 44, in <module>
    unfollow_whitelist=['follow'])
  File "/Users/giovannaparadiso/Desktop/Giovanna/INSTA-BOT/instabot.py-master/src/instabot.py", line 162, in __init__
    fake_ua = UserAgent()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fake_useragent/fake.py", line 69, in __init__
    self.load()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fake_useragent/fake.py", line 78, in load
    verify_ssl=self.verify_ssl,
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fake_useragent/utils.py", line 252, in load_cached
    return read(path)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fake_useragent/utils.py", line 230, in read
    return json.loads(fp.read())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Help me, I'm not so good at this stuffs
```
Include the contents of the error.log here (if applicable).
```

**Comment by ChipWolf** [comment] 2018-04-03 16:44
If this is still an issue, please open a new issue. Thanks!

**Comment by robjimenez30** [comment] 2018-04-13 06:09
I just got this issue too. What do I do?

**Comment by ChipWolf** [comment] 2018-04-15 09:51
Duplicate of #1153

**Closed by ChipWolf** 2018-04-15 09:51 UTC
