### ISSUE TITLE
InstaBot is not defined

### ISSUE THREAD

**Issue by Github1010** [instabot-py/instabot.py#443] opened 2017-03-30 14:07 UTC
I have everything installed.
I copied the text from the website, exactly the same.
![1](https://cloud.githubusercontent.com/assets/26791177/24508135/e19823de-1562-11e7-9228-f530fc40939a.png)
And it says there is an error with InstaBot.
WHat should I do?
![2](https://cloud.githubusercontent.com/assets/26791177/24508156/f0d5fad8-1562-11e7-882b-ece99dbfc2a1.png)

**Comment by ChipWolf** [comment] 2017-03-30 14:20
Duplicate of #442

**Closed by ChipWolf** 2017-03-30 14:20 UTC
