### ISSUE TITLE
Script does not run anymore "login error"

### ISSUE THREAD

**Issue by instabot-master** [instabot-py/instabot.py#1157] opened 2018-04-12 08:19 UTC
## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / **Windows** / Linux / Android

## Python Version?
2 / **3**

## Description

Hi guys, since last night the script in mode "0" is not running anymore due to login error. Could you please advise for a fix. Find the error messages below please:

```
12.04.2018_10:16 Instabot v1.2.0 started at 12.04.2018 10:16:

12.04.2018_10:16 Trying to login as xxx...

12.04.2018_10:17 Login error! Connection error!
12.04.2018_10:17 Removing already liked medias..
12.04.2018_10:17 Trying to unfollow #1:
12.04.2018_10:17 Removing already liked medias..
12.04.2018_10:17 Removing already liked medias..
12.04.2018_10:17 Removing already liked medias..
12.04.2018_10:17 Removing already liked medias..
12.04.2018_10:17 Removing already liked medias..
```

**Comment by ziliangpeng** [comment] 2018-04-12 08:28
@instabot-master eh... nice username!

**Comment by ChipWolf** [comment] 2018-04-12 08:34
Duplicate of #1129

**Closed by ChipWolf** 2018-04-12 08:34 UTC

**Comment by techchannnelandtutorials** [comment] 2018-12-25 00:10
Lol just found soloution to the login error shit. Go to instabot.py line 65 where you will replace the self useragent with your browser's useragent. First login to chrome for an example to your instagram, next head over to https://developers.whatismybrowser.com/useragents/explore click on search which will find your useragent.

**Comment by techchannnelandtutorials** [comment] 2018-12-25 00:11
Lol just found soloution to the login error shit. Go to instabot.py line 65 where you will replace the self useragent with your browser's useragent. First login to chrome for an example to your instagram, next head over to https://developers.whatismybrowser.com/useragents/explore click on search which will find your useragent.

**Comment by dimisdas** [comment] 2018-12-25 00:12
> Lol just found soloution to the login error shit. Go to instabot.py line 65 where you will replace the self useragent with your browser's useragent. First login to chrome for an example to your instagram, next head over to https://developers.whatismybrowser.com/useragents/explore click on search which will find your useragent.

Stop spamming this on all threads. And this is not a solution appropriate to all problems. Please stop.
