### ISSUE TITLE
Instabot returning yml config instead of using it

### ISSUE THREAD

**Issue by maxhoer** [instabot-py/instabot.py#2342] opened 2019-08-06 08:30 UTC
Hello everybody,

we have a little problem using the own config.yml. 

We tried to install the bot in a vm like the new medium article tells about. But when we have to edit the config.yml for entering tags the bot is not running with this changes.

When you instabot-py -c myconfig.yml the bot is only returning the config file into the console.

**Comment by rickyrosso** [comment] 2019-08-06 17:00
i have the same problem, anyone? thanks

**Comment by Fezaro** [comment] 2019-08-07 06:19
Same problem,help would be appreciated.

**Comment by Sunb10ck** [comment] 2019-08-09 04:27
Same boat.  Without a paddle.  Help.

**Comment by Fezaro** [comment] 2019-08-09 05:19
I think I found a way. Use vi to edit the config.yml file just as the medium article says, with your parameters before running instabot-py on the config.yml you have edited. worked for me

**Comment by acollamat** [comment] 2019-08-09 12:16
Got the same problem but I solve it using below. It's just the problem is that the unfollow function is not working and got banned from liking and commenting at around 200 likes. I am using raspberry pi3 on mine.  Since this new update 5.7, I don't have the .yml file. Below is what steps I did.

1. I refer to the medium site below and follow the installations. Created a folder named "Instabot" so it will go in one place.
https://medium.com/@asker_amine/whats-new-in-the-instagram-bot-0-5-2-fe52154fdc8a

2. Follow these command below and install the instabot on that folder. You can refer the video in the Medium site above.

#Install python3-venv to create virtual env
# In Ubuntu, install it using apt
sudo apt install python3-venv 
# Create a virtual env 
python3 -m venv venv 
source venv/bin/activate
pip install instabot-py
instabot-py --version 

3. Downloaded the Instabot zip from the github site and copied the sample.instabot.config.yml and put in instabot folder where the venv and other located.
4. Edit the sample.instabot.config.yml with my login and settings.
5. Followed the other video in Medium site on how to edit the yml
6. Then run the instabot. Also buy renaming the sample.instabot.config.yml to instabot.config.yml is that you can run the bot by typing instabot-py.

**Comment by Sunb10ck** [comment] 2019-08-09 16:39
@Fezaro  Tried ~20 times with this method and it just prints the file and exits back to console.

@acollamat This is really interesting.  The downloaded zip's sample.instabot.config.yml is **completely different** than the myconfig.yml file.

The sample.instabot.config.yml looks like:

---
login : "username"
password : "password"
debug: 0
follow_time: 604800
like_per_day: 709
comments_per_day: 31
max_like_for_one_tag: 36
follow_per_day: 260
follow_time: 36000
unfollow_per_day: 247
unfollow_break_min: 3
unfollow_break_max: 17
unfollow_selebgram: false
unfollow_probably_fake: true
unfollow_inactive: true
unfollow_recent_feed: false

and that is it... no space for tags, parameters, etc.
whereas the original myconfig.yml looks like:

accept_language: en-US,en;q=0.5
ban_sleep_time: 10800
comment_list:
- - this
  - the
  - your
- - photo
  - picture
  - pic
  - shot
  - snapshot
- - is
  - looks
  - feels
  - is really
- - great
  - super
  - good
  - very good
  - good
  - wow
  - WOW
  - cool
  - GREAT
  - magnificent
  - magical
  - very cool
  - stylish
  - beautiful
  - so beautiful
  - so stylish
  - so professional
  - lovely
  - so lovely
  - very lovely
  - glorious
  - so glorious
  - very glorious
  - adorable
  - excellent
  - amazing
- - .
  - ..
  - '...'
  - '!'
  - '!!'
  - '!!!'
comments_per_day: 0
comments_per_run: '{{comments_per_day}}'
config:
  file: instabot2.config.yml
database:
  connection_string: sqlite:///{{database.path}}
  path: '{{login}}.db'
  type: sql
debug: 0
dump_configuration: true
end_at_h: 23
end_at_m: 59
error_400_to_ban: 3
follow_per_day: 0
follow_per_run: '{{follow_per_day}}'
follow_time: 18000
follow_time_enabled: true
like_per_day: 777
like_per_run: '{{like_per_day}}'
list_of_ua:
- Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; FSL 7.0.6.01001)
- Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; FSL 7.0.7.01001)
- Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; FSL 7.0.5.01003)
- Mozilla/5.0 (Windows NT 6.1; WOW64; rv:12.0) Gecko/20100101 Firefox/12.0
- Mozilla/5.0 (X11; U; Linux x86_64; de; rv:1.9.2.8) Gecko/20100723 Ubuntu/10.04 (lucid)
  Firefox/3.6.8
- Mozilla/5.0 (Windows NT 5.1; rv:13.0) Gecko/20100101 Firefox/13.0.1
- Mozilla/5.0 (Windows NT 6.1; WOW64; rv:11.0) Gecko/20100101 Firefox/11.0
- Mozilla/5.0 (X11; U; Linux x86_64; de; rv:1.9.2.8) Gecko/20100723 Ubuntu/10.04 (lucid)
  Firefox/3.6.8
- Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0; .NET CLR 1.0.3705)
- Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)
- Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/4.0; .NET CLR 2.0.50727;
  .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729)
- Opera/9.80 (Windows NT 5.1; U; en) Presto/2.10.289 Version/12.01
- Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; SV1; .NET CLR 2.0.50727)
- Mozilla/5.0 (Windows NT 5.1; rv:5.0.1) Gecko/20100101 Firefox/5.0.1
- Mozilla/5.0 (Windows NT 6.1; rv:5.0) Gecko/20100101 Firefox/5.02
- Mozilla/5.0 (Windows NT 6.0) AppleWebKit/535.1 (KHTML, like Gecko) Chrome/13.0.782.112
  Safari/535.1
- Mozilla/4.0 (compatible; MSIE 6.0; MSIE 5.5; Windows NT 5.0) Opera 7.02 Bork-edition
  [en]
log_mod: 1
logging:
  disable_existing_loggers: false
  formatters:
    simple:
      format: '%(asctime)s - {{login}} - %(name)s - %(levelname)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: simple
      level: DEBUG
      stream: ext://sys.stdout
  loggers:
    InstaBot:
      handlers:
      - console
      level: DEBUG
      propagate: 'no'
    Persistence:
      handlers:
      - console
      level: DEBUG
      propagate: 'no'
  root:
    level: INFO
  version: 1
max_like_for_one_tag: 5
media_max_like: 0
media_min_like: 0
proxies: {}
session_file: '{{login}}.session'
start_at_h: 0
start_at_m: 0
tag_blacklist: []
tag_list:
- cat
- car
- dog
time_till_unlike: 259200
unfollow_break_max: 30
unfollow_break_min: 15
unfollow_everyone: false
unfollow_inactive: false
unfollow_not_following: true
unfollow_per_day: 5
unfollow_per_run: '{{unfollow_per_day}}'
unfollow_probably_fake: true
unfollow_recent_feed: true
unfollow_selebgram: false
unfollow_whitelist: []
unlike_per_day: 0
unlike_per_run: '{{unlike_per_day}}'
unwanted_username_list: []
user_blacklist: {}
user_max_follow: 0
user_min_follow: 0
window_check_every: 300

My obvious question is how does one .yml contain the login/pass while the other doesn't?  And how does one .yml contain the parameters while the other doesn't?  What command is actually going to run the bot with my settings?

I can get the bot to run, but it just keeps liking cats, dogs, and cars.

**Comment by acollamat** [comment] 2019-08-09 17:28
@Sunb10ck 
I added a tag list in the top. Like below format. The instabot is using the default format since you did not add the taglist.

tag_list ['photooftheday','selfie']

**Comment by SohaibS2E** [comment] 2019-08-09 19:33
This parameter solved the problem for me:
```
dump_configuration: false
```

**Comment by Elektrokid1** [comment] 2019-08-09 21:47
I ask some help !
the bot is running on the default settings on **default_config .py** so he like "cat dog and car" 
<img width="709" alt="Screenshot 2019-08-09 at 23 37 21" src="https://user-images.githubusercontent.com/52871117/62810698-15ff7200-baff-11e9-95b5-14bab4274f13.png">
<img width="707" alt="Screenshot 2019-08-09 at 23 36 48" src="https://user-images.githubusercontent.com/52871117/62810705-1bf55300-baff-11e9-8414-343d3a685a0b.png">
 so ive create **myconfig.yml** , everything is fine but My question is ..... where are the comments , tag list , black list etcetera ... ive missed someting ? 

can someone make an updated tutorial to "how to edit myconfig.yml" 

because I'm lost and I think I'm not the only one 

Thanks

**Comment by yurilaaziz** [comment] 2019-08-12 22:08
fixed in the 0.5.8, please update

**Closed by yurilaaziz** 2019-08-12 22:08 UTC
