### ISSUE TITLE
KeyError: 'media'

### ISSUE THREAD

**Issue by pryetranka** [instabot-py/instabot.py#481] opened 2017-04-17 20:00 UTC
Out of nowhere got this error. Occurs right after the login when bot tries to follow someone, then instantly unfollows for some strange reason. Tried to run with unmodified instabot.py and original example.py with my login, still same results.

````
Trying to follow: 4555305942
Followed: 4555305942 #1.
Traceback (most recent call last):
  File "youngspinach.py", line 68, in <module>
    bot.new_auto_mod()
  File "/home/pi/instabot.py/src/instabot.py", line 564, in new_auto_mod
    self.new_auto_mod_comments()
  File "/home/pi/instabot.py/src/instabot.py", line 619, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['code']) == False:
  File "/home/pi/instabot.py/src/instabot.py", line 648, in check_exisiting_comment
    if all_data['media']['owner']['id'] == self.user_id:
KeyError: 'media'
Trying to unfollow: 4555305942
Unfollow: 4555305942 #1 of 1.
Pausing for 67 seconds... 1 of 1
Logout: likes - 1, follow - 1, unfollow - 1, comments - 0.
Bot work time: 0:01:22.818982
Logout success!
Exception KeyError: KeyError(1995988992,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
````

**Comment by petergriffin1986** [comment] 2017-04-17 20:02
I can attest to this, came here to create this same exact issue. It started happening something like two hours ago. I had to stop commenting for now.

**Comment by pryetranka** [comment] 2017-04-17 20:09
@petergriffin1986 Glad I'm not alone. I guess Instagram changed something then...

**Comment by phrozendice** [comment] 2017-04-17 20:13
Same happening here, looks like it started happening sometime after lunch (EST)

**Comment by nicholaai** [comment] 2017-04-17 20:14
+1

**Comment by alvinlee123** [comment] 2017-04-17 20:39
Issue here from the like_util.py lines 60/61
`user_name = browser.execute_script("return window._sharedData.entry_data.PostPage[0].media.owner.username")
  image_text = browser.execute_script("return window._sharedData.entry_data.PostPage[0].media.caption")`

**Comment by nicholaai** [comment] 2017-04-17 23:41
Turned off follow / unfollow and problem persists.

**Comment by bangarang** [comment] 2017-04-18 06:23
Looks like its a problem in the check_exisiting_comment method. I stopped doing that and it continues to work. Looking into what's causing that....

**Comment by Bellman281** [comment] 2017-04-18 06:27
what did u do?

**Comment by bangarang** [comment] 2017-04-18 06:45
You can just comment out the line that calls check_exisiting_comment, or modify it to use the new format.

It looks like the url_media_detail changed format to use graphql. This seems to be working for me: 

```
    def check_exisiting_comment(self, media_code):
        url_check = self.url_media_detail % (media_code)
        check_comment = self.s.get(url_check)
        all_data = json.loads(check_comment.text)
        if all_data['graphql']['shortcode_media']['owner']['id'] == self.user_id:
                self.write_log("Keep calm - It's your own media ;)")
                # Del media to don't loop on it
                del self.media_by_tag[0]
                return True
        comment_list = list(all_data['graphql']['shortcode_media']['edge_media_to_comment']['edges'])
        for d in comment_list:
            if d['owner']['id'] == self.user_id:
                self.write_log("Keep calm - Media already commented ;)")
                # Del media to don't loop on it
                del self.media_by_tag[0]
                return True
        return False 
```

**Comment by julianjuko** [comment] 2017-04-18 07:21
@bangarang Thanks for this code, I updated instabot.py with it but occasionally get the following:

`2017-04-18 17:14:25,985 - elonmusk - Traceback (most recent call last):
  File "/home/julian/repos/instabot/src/instabot.py", line 983, in unfollow_loop
    self.new_auto_mod_comments()
  File "/home/julian/repos/instabot/src/instabot.py", line 606, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['code']) == False:
  File "/home/julian/repos/instabot/src/instabot.py", line 655, in check_exisiting_comment
    if d['owner']['id'] == self.user_id:
KeyError: 'owner'`

However if I catch the exception and continue to run the bot it comments successfully most other times. As I'm completely unfamiliar with graphql, I was wondering if you'd know what the cause of this is.

**Comment by bangarang** [comment] 2017-04-18 07:25
@julianjuko Yeah, I just got that too. Looks like I was a little off on the comment loop.

Try this: 
```
    def check_exisiting_comment(self, media_code):
        url_check = self.url_media_detail % (media_code)
        check_comment = self.s.get(url_check)
        all_data = json.loads(check_comment.text)
        if all_data['graphql']['shortcode_media']['owner']['id'] == self.user_id:
                self.write_log("Keep calm - It's your own media ;)")
                # Del media to don't loop on it
                del self.media_by_tag[0]
                return True
        comment_list = list(all_data['graphql']['shortcode_media']['edge_media_to_comment']['edges'])
        for d in comment_list:
            if d['node']['owner']['id'] == self.user_id:
                self.write_log("Keep calm - Media already commented ;)")
                # Del media to don't loop on it
                del self.media_by_tag[0]
                return True
        return False
```

Graphql is just what instagram is using on their end to create this json response. It must have changed recently to a new format that caused this.

**Comment by wladneto** [comment] 2017-04-18 10:44
@bangarang Great! It´s Work for me!

**Comment by JacobGarcia** [comment] 2017-04-19 04:09
Thanks a lot @bangarang. Yes, it looks like IG changed their format response. Gladly you have found the new JSON format. Really, thanks again!

**Comment by man2** [comment] 2017-04-19 11:17
should be committed to main repo

**Comment by nicholaai** [comment] 2017-04-19 22:39
I believe there is still an issue here. The bot has shut down after a while even with the change by @bangarang

**Comment by KLQCKY** [comment] 2017-05-07 00:20
@bangarang huh for some reason examply.py just flashes on the screen for a second and closes after I used your fix.

**Comment by ChipWolf** [comment] 2017-05-09 14:58
@bangarang for the billionth time. When this happens, make a PR! Thanks

**Comment by artemdumanov** [comment] 2017-05-11 06:03
Check this one https://github.com/artemdumanov/instabot.py

2017-05-09 17:58 GMT+03:00 <notifications@github.com>:

**Comment by papaaaa211** [comment] 2017-08-02 06:19
gg

**Comment by ugurozturk** [comment] 2018-01-11 21:44
Major changes have been made to Instabot.py. If this is still an issue, please open a new ticket.

**Closed by ugurozturk** 2018-01-11 21:44 UTC
