### ISSUE TITLE
ValueError: Attempted relative import in non-package

### ISSUE THREAD

**Issue by faniefikri** [instabot-py/instabot.py#891] opened 2018-01-12 06:53 UTC
Fill all requirements before sending issues. Or all issues will be closed without reading. 

- [v] Searched and checked other issues about my problem
[Terminal Saved Output.txt](https://github.com/instabot-py/instabot.py/files/1625148/Terminal.Saved.Output.txt)

- [v] If have errors.log file and i did upload it

Check One :
- [v] Bug
- [ ] Feature
- [ ] Need Help

## What OS ?
MAC 
## Python Version ?
3.5
## Is it VPS ?
No
### VPS: Is the vps far far away ? Another Country ?
No
- [x] VPS: Tried the same code via my local pc

**Comment by ugurozturk** [comment] 2018-01-12 09:00
duplicate of https://github.com/instabot-py/instabot.py/issues/886

**Closed by ugurozturk** 2018-01-12 09:00 UTC
