### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by isaiahnields** [instabot-py/instabot.py#1177] opened 2018-04-13 22:28 UTC
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [ X] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [ X] Bug
- [ ] Technical Help
- [ ] Other
- [ ] Feature Request

### Operating System? (include version)

Raspbian GNU/Linux 9.3 (stretch)

## Python Version?
3

## Description

This error occurs on login. This issue has been previously opened but was incorrectly closed for being the same as another issue.

```
Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/home/pi/Documents/instabot.py/src/instabot.py", line 231, in __init__
    self.login()
  File "/home/pi/Documents/instabot.py/src/instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/home/pi/Documents/instabot.py/src/userinfo.py", line 41, in get_user_id_by_login
    all_data = json.loads(info.text)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by someplace11** [comment] 2018-04-13 22:44
Mine flagged the same errors this morning. It was working great like 3 days before.

**Comment by davidmantegna** [comment] 2018-04-13 23:14
Change line 300 in instabot.py:

`self.user_id = ui.get_user_id_by_login(self.user_login)`
to
`self.user_id = 1599282551`

**Comment by joilson-cisne** [comment] 2018-04-14 04:11
You can use https://socialblade.com for getting the user_id.

**Comment by Tonners15** [comment] 2018-04-14 17:55
@davidmantegna  fixed works fine altho the link is not working here is a new one where you can find your userID https://codeofaninja.com/tools/find-instagram-user-id

**Comment by ChipWolf** [comment] 2018-04-14 21:00
Duplicate of #1153

**Closed by ChipWolf** 2018-04-14 21:00 UTC
