### ISSUE TITLE
extensive data usage

### ISSUE THREAD

**Issue by farhang87** [instabot-py/instabot.py#159] opened 2016-08-17 04:38 UTC
I run the bot via terminal on my mac at midnight. Been tracking my data usage via Bandwidth+ while closing all other apps and the instabot used 20-25GB Downstream in 10 hours with abt 200 likes. That's pretty much isn't it? Any way to make this less, I am reaching almost my monthly quota of 1TB.

**Comment by Burgg** [comment] 2016-08-22 07:43
is this confirmed?

**Comment by LevPasha** [comment] 2016-08-31 07:33
@farhang87 @Burgg wow-wow-wow, 20 GB???!!!! I don't test how many data bot use, but 1 request to like take about 200-300 B. 

Someone can make this test?

**Comment by polaroi8d** [comment] 2016-08-31 10:25
If i have a free-time I will check it.

**Comment by mmaton** [comment] 2016-09-16 17:08
yesterday     45.54 MiB  /  537.33 MiB  /  582.86 MiB

**Comment by polaroi8d** [comment] 2016-09-19 09:02
Hmmm intresting, thanks for your test @mmaton

**Comment by LevPasha** [comment] 2016-09-19 12:23
@mmaton i don't understand about this data) 45 MiB at day or 580? Two bots with what setting (like count, follow count, etc)? 

THX!

**Comment by ChipWolf** [comment] 2017-04-03 09:57
Closing for now, this looks like an isolated issue

**Closed by ChipWolf** 2017-04-03 09:57 UTC
