### ISSUE TITLE
Error on start - File "example.py", line 9, in <module>

### ISSUE THREAD

**Issue by fadriPi** [instabot-py/instabot.py#903] opened 2018-01-13 17:30 UTC
> Fill in all requirements *before* submitting an issue. If you fail to do so, we will close the ticket.

- [x] This is a checked box.
- [ ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ x] If so; have you tried running the code on your local machine?

#### Select one:
- [x ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android
Windows

## Python Version?
2 / 3
3
## Description
Error with starting the bot.

Type the description of your issue here.
I set username and password and added users to unfollowing whitelist. 
after starting the bot with "python example.py" I got the following error:

Traceback (most recent call last):
  File "example.py", line 9, in <module>
    from check_status import check_status
  File "C:\Users\administrator.MELCHER\Downloads\instabot.py-master\instabot.py-master\src\check_status.py", line 3, in <module>
    from .user_info import get_user_info
ImportError: attempted relative import with no known parent package

Include the contents of the error.log here (if applicable).
```

**Comment by ugurozturk** [comment] 2018-01-13 18:31
@fadriPi duplicate of https://github.com/instabot-py/instabot.py/issues/886

**Closed by ugurozturk** 2018-01-13 18:31 UTC
