### ISSUE TITLE
InstaBot - ERROR - 'graphql'

### ISSUE THREAD

**Issue by nicolaceliento** [instabot-py/instabot.py#2445] opened 2019-10-28 19:13 UTC
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [X] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [ ] If so, have you tried running the code on your local machine?

```
Using Python 3.8.0 on Windows 10 and installed InstaBot from repo with the following command:

python3 -m pip install instabot-py

```

#### Operating System? (include version)
- [ ] macOS
- [X] Windows
- [ ] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
include the output of 'uname -a'
```

#### Python Version Requirement
- [X] I am using Python 3.6 or above

#### Exact Python Version?
3.8.0
Include here the response of 'python --version' or 'python3 --version'
Python 3.8.0

#### Pip Version?
19.3.1
Include here the response of 'pip --version' or 'pip3 --version'
pip 19.3.1 from c:\users\username\appdata\local\programs\python\python38-32\lib\site-packages\pip (python 3.8)

#### Instabot Version?
```
Include here the response of 'instabot-py --version'
```

#### How you use the instabot
- [ ] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [X] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue

2019-10-28 19:28:50,379 - InstaBot - WARNING - Couldn't comment post, resuming. https://www.instagram.com/p/B4LANNqIvcL/
2019-10-28 19:28:50,380 - InstaBot - ERROR - 'graphql'
Traceback (most recent call last):
  File "c:\users\username\appdata\local\programs\python\python38-32\lib\site-packages\instabot_py\instabot.py", line 1117, in check_exisiting_comment
    self.current_owner = all_data["graphql"]["shortcode_media"]["owner"][
KeyError: 'graphql'

#### Config

like_per_day = 30
comments_per_day = 10
max_like_for_one_tag = 5
follow_per_day = 10
follow_time = 18600
unfollow_per_day = 10
unfollow_selebgram = True
unfollow_probably_fake = True
unfollow_inactive = True
unfollow_recent_feed = True

**Comment by hadouken111** [comment] 2019-10-29 20:14
Same Issue for me :/

**Comment by mrallanodreman** [comment] 2019-10-29 21:53
Just in comment!

**Comment by MONEBRE** [comment] 2019-10-30 18:41
How to disable comments then pls help. Thanks in advance.

**Comment by elmissouri16** [comment] 2019-10-30 18:43
> 
> 
> How to disable comments then pls help. Thanks in advance.

its pretty simple just set comments_per_day to 0 ,

**Comment by jonkoss** [comment] 2019-10-30 18:45
> 
> 
> this happens only on comments so for the people who arent using simply dont use comments and its should be fine

Thanks heaps buddy !

**Comment by loganyc1934** [comment] 2019-10-31 01:51
Same, currently disabling comment but would like to see a fix soon. Following. Thanks!

**Comment by cyberpuppet** [comment] 2019-10-31 21:38
Same Problem i am facing here !!

**Comment by Viktor19931** [comment] 2019-11-05 09:13
I have the same problem with comments!

**Comment by claudiofrancesconi** [comment] 2019-11-07 09:14
same problem with comments

**Comment by nickgryg** [comment] 2019-11-17 03:59
Duplicate of #2442

**Closed by nickgryg** 2019-11-17 03:59 UTC
