### ISSUE TITLE
following isnt working anymore

### ISSUE THREAD

**Issue by Tidle999** [instabot-py/instabot.py#1127] opened 2018-04-04 14:02 UTC
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [X] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
Windows 10

## Python Version?
3

## Description

Following isnt working anymore. it just tells me trying to follow but nothing happens.
i tried with the newest commit and also with my old that worked earlier. problem seems to be new, it worked yesterday.
liking, commenting and unfollowing is working.
tested with mode 0 / 2 / 4
also tested with clearing followers_db.db

```
   >>>This account is following you
   >>>You are following this account

04.04.2018_15:55 Get media id by tag: berlinblogger
04.04.2018_15:55 Removing already liked medias..
04.04.2018_15:55 Trying to like media: 1750109216003390012
04.04.2018_15:55 Liked: 1750109216003390012. Like #1.
04.04.2018_15:55 Trying to follow: 6263671675
04.04.2018_15:55 Trying to unfollow #1:
04.04.2018_15:55 Looks like there is nobody to unfollow.
04.04.2018_15:56 Trying to unfollow #1:
04.04.2018_15:56 Looks like there is nobody to unfollow.
04.04.2018_15:56 Trying to follow: 6263671675
04.04.2018_15:56 Trying to unfollow #1:
04.04.2018_15:56 Looks like there is nobody to unfollow.
04.04.2018_15:56 Trying to like media: 1750108067191768786
04.04.2018_15:56 Liked: 1750108067191768786. Like #2.
04.04.2018_15:56 Trying to unfollow #1:
04.04.2018_15:56 Looks like there is nobody to unfollow.
04.04.2018_15:57 Trying to follow: 22724586
04.04.2018_15:57 Trying to unfollow #1:
04.04.2018_15:57 Looks like there is nobody to unfollow.
04.04.2018_15:57 Trying to like media: 1750097973557176545
04.04.2018_15:57 Liked: 1750097973557176545. Like #3.
04.04.2018_15:57 Trying to unfollow #1:
04.04.2018_15:57 Looks like there is nobody to unfollow.
04.04.2018_15:58 Trying to follow: 1176161529
04.04.2018_15:58 Trying to unfollow #1:
04.04.2018_15:58 Looks like there is nobody to unfollow.
04.04.2018_15:58 Trying to unfollow #1:
04.04.2018_15:58 Looks like there is nobody to unfollow.
04.04.2018_15:58 Trying to like media: 1750092527439901778
04.04.2018_15:58 Liked: 1750092527439901778. Like #4.
04.04.2018_15:58 Trying to follow: 3558268380
04.04.2018_15:58 Trying to unfollow #1:
04.04.2018_15:58 Looks like there is nobody to unfollow.
04.04.2018_15:59 Trying to unfollow #1:
04.04.2018_15:59 Looks like there is nobody to unfollow.
04.04.2018_15:59 Trying to like media: 1750089760371910381
04.04.2018_15:59 Liked: 1750089760371910381. Like #5.
04.04.2018_15:59 Trying to follow: 1383719567
04.04.2018_15:59 Trying to unfollow #1:
04.04.2018_15:59 Looks like there is nobody to unfollow.
04.04.2018_16:00 Trying to unfollow #1:
04.04.2018_16:00 Looks like there is nobody to unfollow.
04.04.2018_16:00 Trying to follow: 1383719567
04.04.2018_16:00 Trying to unfollow #1:
04.04.2018_16:00 Looks like there is nobody to unfollow.
04.04.2018_16:00 Trying to like media: 1750081434368166944
04.04.2018_16:00 Liked: 1750081434368166944. Like #6.
04.04.2018_16:01 Trying to unfollow #1:
04.04.2018_16:01 Looks like there is nobody to unfollow.
04.04.2018_16:01 Trying to follow: 3966792389
```

**Comment by darynk** [comment] 2018-04-07 20:54
Same

**Comment by MarrenDartin** [comment] 2018-04-08 23:53
Following isn't working for me as well

**Comment by ChipWolf** [comment] 2018-04-10 10:24
I'll try and replicate this issue. If anyone else finds the root cause, let me know down below.

**Comment by instabot-master** [comment] 2018-04-10 21:03
the unfollow of mode 0 is working for me; however, the pure unfollowing functionality of mode 5 is not working recently anymore. the window closes immediately when starting the script.

**Comment by ChipWolf** [comment] 2018-04-11 13:07
Mode 0 is the only supported mode currently

**Comment by itkos** [comment] 2018-04-13 14:46
in mode 0 dont unfollow, in console write a whole hour:
13.04.2018_17:12 Trying to unfollow #1:
......

**Comment by ChipWolf** [comment] 2018-04-15 09:53
Duplicate of #1174

**Closed by ChipWolf** 2018-04-15 09:53 UTC
Labels: priority/high, status/review-needed, type/bug
