### ISSUE TITLE
Start Problems.

### ISSUE THREAD

**Issue by thecompix** [instabot-py/instabot.py#1167] opened 2018-04-13 09:19 UTC
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [x] Are you hosting the bot on a VPS or other Cloud hosting? (RPI)
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [?] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
Linux

## Python Version?
2 / 3

## Description

Hey Guys,

since this morning the bots doent start.

Traceback (most recent call last):
  File "bot.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/root/tronix/src/instabot.py", line 231, in __init__
    self.login()
  File "/root/tronix/src/instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/root/tronix/src/userinfo.py", line 41, in get_user_id_by_login
    all_data = json.loads(info.text)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

What is the Problem?

**Comment by mindfreakz** [comment] 2018-04-13 09:49
same error for me and some others.

**Comment by ChipWolf** [comment] 2018-04-13 09:56
Duplicate of #1153

**Closed by ChipWolf** 2018-04-13 09:56 UTC
