### ISSUE TITLE
Different Modes not Working

### ISSUE THREAD

**Issue by fillipemontenegro** [instabot-py/instabot.py#716] opened 2017-08-23 18:46 UTC
Do these modes work or will they work soon?

I've tried both modes 1 and 2 and all I get is 

"Except on get_info!" for mode 1

"Except on get_info!
XXXXXXX Except on get_media! XXXXXXX" for mode 2

What I wanted was:
Follow based on tags;
Unfollow fakes, celebrities;
Unfollow those who don't follow back;

Mode 0 seems to unfollow everyone, either they follow me back or not.
Any tips on where to tinker to achieve this?

Thanks!

**Comment by ugurozturk** [comment] 2018-01-13 11:26
this is old so going to make this as duplicate of https://github.com/instabot-py/instabot.py/issues/899

**Closed by ugurozturk** 2018-01-13 11:26 UTC
Labels: status/revision-needed, type/bug
