### ISSUE TITLE
Error when Logging in Execpt on check version. + Traceback

### ISSUE THREAD

**Issue by bootexe** [instabot-py/instabot.py#1164] opened 2018-04-13 06:33 UTC
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC 10.13.4

## Python Version?
2 

## Description

the client is trying to logging but I've got an error message from python and I can't fix it

08:29 Instaboost v2.19.0 started at 13.04.2018 08:29:

Exception on Check Version
08:29 Trying to login as bootexe...

Traceback (most recent call last):
  File "example.py", line 55, in <module>
    unfollow_whitelist=['xxxx']) 
  File "/Users/raphael/instaboost/Instaboost/src/instabot.py", line 241, in __init__
    self.login()
  File "/Users/raphael/instaboost/Instaboost/src/instabot.py", line 319, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/Users/raphael/instaboost/Instaboost/src/userinfo.py", line 43, in get_user_id_by_login
    all_data = json.loads(info.text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```
error.log is empty

**Comment by chrisoname** [comment] 2018-04-13 07:58
Same issue here.

**Comment by mykesimon** [comment] 2018-04-13 08:07
I got the same issue. Any idea why??

**Comment by ChipWolf** [comment] 2018-04-13 08:44
Duplicate of #1154

**Closed by ChipWolf** 2018-04-13 08:44 UTC
