### ISSUE TITLE
KeyError graphql

### ISSUE THREAD

**Issue by zeeebbbrrraaa** [instabot-py/instabot.py#2448] opened 2019-11-02 06:53 UTC
2019-11-02 13:53:24,903 - InstaBot - WARNING - Couldn't comment post, resuming. https://www.instagram.com/p/B4WRCZehpZs/
2019-11-02 13:53:24,904 - InstaBot - ERROR - 'graphql'
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/instabot_py/instabot.py", line 1117, in check_exisiting_comment
    self.current_owner = all_data["graphql"]["shortcode_media"]["owner"][
KeyError: 'graphql'

**Comment by Viktor19931** [comment] 2019-11-05 09:25
have same issue (

**Comment by prameshbajra** [comment] 2019-11-09 17:06
### GETTING SAME ISSUE

Did Instagram APIs update from REST to GRAPHQL?
I have a hunch that this error started happening from the last app update.

@Viktor19931 @zeeebbbrrraaa  Did you guys happen to find a workaround for this?

**Comment by thecatextremist** [comment] 2019-11-10 04:33
Instagram is being a fucking cunt!

**Comment by anisghalmi** [comment] 2019-11-11 16:14
https://publishers.propellerads.com/#/pub/auth/signUp?ref_id=ZC8f
If you want to earn money use it

**Comment by kotrakesh** [comment] 2019-11-13 14:10
Getting same error,  comment failure but rest works

**Comment by wahengchang** [comment] 2019-11-14 09:27
have same issue (

**Comment by nickgryg** [comment] 2019-11-17 04:00
Duplicate of #2442

**Closed by nickgryg** 2019-11-17 04:00 UTC

**Comment by Viktor19931** [comment] 2020-01-30 20:28
@prameshbajra  I have same issue
