### ISSUE TITLE
Login error !

### ISSUE THREAD

**Issue by GeoffreyPG** [instabot-py/instabot.py#2053] opened 2019-03-22 01:47 UTC
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [x] macOS
- [ ] Windows
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
3.7.2
```

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```

#### Description of your issue

```
My login details are correct, i checked several times and i don't use my mail for username. 

     ______Starting bot_____
22.03.2019_02:33 Checking for updates...
22.03.2019_02:33 You are running the latest stable version
22.03.2019_02:33 Instabot v1.2.4/0 started at 22.03.2019 02:33:
22.03.2019_02:33 Trying to login as ...
22.03.2019_02:33 Something wrong with login
22.03.2019_02:33 {"authenticated": false, "user": true, "status": "ok"}
22.03.2019_02:33 Login error! Check your login data!
22.03.2019_02:33 Exit Program... GoodBye
```

#### Config

```
username = 
password = 
start_at_h = 8
start_at_m = 0
end_at_h = 0
end_at_m = 0
session_file = "username.session"
like_per_day = 1000
comments_per_day = 0
max_like_for_one_tag = 50
follow_per_day = 500
follow_time = 54000
user_min_follow = 0
user_max_follow = 5000
unfollow_per_day = 500
tag_list = ["modehomme", "stylemen"]
max_like_for_one_tag = 5
unfollow_break_min = 15
unfollow_break_max = 30
unfollow_not_following = True
unfollow_selebgram = False
unfollow_probably_fake = True
unfollow_inactive = True
unfollow_recent_feed = True
unwanted_username_list = ["second", "stuff", "art", "project", "love", "life", "food", "blog", "free", "keren", "photo", "graphy", "indo", "travel", "art", "shop", "store", "sex", "toko", "jual", "online", "murah", "jam", "kaos", "case", "baju", "fashion", "corp", "tas", "butik", "grosir", "karpet", "sosis", "salon", "skin", "care", "cloth", "tech", "rental", "kamera", "beauty", "express", "kredit", "collection", "impor", "preloved", "follow", "follower", "gain", ".id", "_id", "bags"]
```

**Comment by dimisdas** [comment] 2019-03-22 06:12
Your login is probably wrong. There has been 3 instances this week that someone messaged me on the Telegram group, insisting vehemently that everything was correct and they had double checked or tripled check, and there was zero possibility that they had entered the wrong details, zero!

Turns out they had either used the wrong password, or had a typo in username (you shouldn’t add @ sign either.)

However, because I never wish to discredit anyone, I checked it myself this morning. Just to be sure. My old account still logins just fine. I also created a new dummy account, it also works. There also haven’t been any other complaints on the Telegram group.

Could you please try to manually copy/paste your password to www.Instagram.com and make sure it’s correct? Do not make multiple wrong login attempts with the bot or web browser, because this will naturally get you locked out. 

If that doesn’t work, please let me know and I’ll send you a special version of Instabot.py that will output more debugging messages.

**Comment by GeoffreyPG** [comment] 2019-03-22 07:31
I try to copy/paste to instagram and it’s correct. I have the same message this morning on instabot.

Cordialement,

Poilly Geoffrey
________________________________
De : Dimis <notifications@github.com>
Envoyé : Friday, March 22, 2019 7:12:59 AM
À : instabot-py/instabot.py
Cc : GeoffreyPG; Author
Objet : Re: [instabot-py/instabot.py] Login error ! (#2053)


Your login is probably wrong. There has been 3 instances this week that someone messaged me on the Telegram group, insisting vehemently that everything was correct and they had double checked or tripled check, and there was zero possibility that they had entered the wrong details, zero!

Turns out they had either used the wrong password, or had a typo in username (you shouldn’t add @ sign either.)

However, because I never wish to discredit anyone, I checked it myself this morning. Just to be sure. My old account still logins just fine. I also created a new dummy account, it also works. There also haven’t been any other complaints on the Telegram group.

Could you please try to manually copy/paste your password to www.Instagram.com<http://www.Instagram.com> and make sure it’s correct? Do not make multiple wrong login attempts with the bot or web browser, because this will naturally get you locked out.

If that doesn’t work, please let me know and I’ll send you a special version of Instabot.py that will output more debugging messages.

**Comment by dimisdas** [comment] 2019-03-22 07:41
Do you have 2 Factor Authentication enabled?

Like I said I’m unable to reproduce this. Does the issue also persist on a new account ?

**Comment by GeoffreyPG** [comment] 2019-03-22 07:54
Don't have 2 factor authentication.
I try with a new account and it works.

**Comment by GeoffreyPG** [comment] 2019-03-22 08:10
what i can do with my old account ?

**Comment by dimisdas** [comment] 2019-03-22 18:28
Closing this since it was resolved over Telegram.

For people who might read this in the future:

User was editing a different config.ini than the active one. If you are having similar issues, make sure your config is located in your current directory.

**Closed by dimisdas** 2019-03-22 18:28 UTC
