### ISSUE TITLE
Sotped ? My won't log in !!!! Login error 

### ISSUE THREAD

**Issue by levisoares** [instabot-py/instabot.py#866] opened 2018-01-02 22:15 UTC
As soon as i run the script.. there is an error. Any clues

root@Kronos:~# python scripts/instabot.py/levi.py                          Instabot v1.1.0 started

Trying to login as levijsoares...

Traceback (most recent call last):
  File "scripts/instabot.py/levi.py", line 43, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/root/scripts/instabot.py/src/instabot.py", line 189, in __init__
    self.login()
  File "/root/scripts/instabot.py/src/instabot.py", line 239, in login
    r = self.s.get(self.url)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb6bb8d8c>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
root@Kronos:~#

**Comment by GithubProgress** [comment] 2018-01-11 20:50
This seems to be a connectivity issue . If you think it is another reason , please open a new issue with the console output and your bot settings .

**Comment by levisoares** [comment] 2018-01-11 22:04
It's not.. this is a online Linux server.. worked fine.. from one day to another... stoped... when i tried to start it.. this was the output

**Comment by HenryCooperGithub** [comment] 2018-01-11 22:06
So this is a constant issue ? If it is please re-download instabot.py into a new folder with the default settings and let me know if that helps

**Comment by levisoares** [comment] 2018-01-11 23:44
I re-downloaded and tryed again.. this was the output:

root@Kronos:~# python scripts/instabot.py/levi.py
Traceback (most recent call last):
  File "scripts/instabot.py/levi.py", line 9, in <module>
    from check_status import check_status
  File "/root/scripts/instabot.py/src/check_status.py", line 3, in <module>
    from .user_info import get_user_info
ValueError: Attempted relative import in non-package
root@Kronos:~#

**Comment by HenryCooperGithub** [comment] 2018-01-12 00:03
Please use the example.py not your custom version .

**Comment by levisoares** [comment] 2018-01-12 00:06
its the same.. i just renamed

**Comment by HenryCooperGithub** [comment] 2018-01-12 00:08
Please update to the most recent version of instabot.py

If your problem still persists attach the following information:

- Your bot configuration (parameters)
- Full console output

**Comment by levisoares** [comment] 2018-01-12 00:12
i already did updated to the latest version..
 gonna paste everything

**Comment by ugurozturk** [comment] 2018-01-12 01:33
duplicate of https://github.com/instabot-py/instabot.py/issues/886

**Closed by ugurozturk** 2018-01-12 01:33 UTC
Labels: type/question

**Comment by ugurozturk** [comment] 2018-01-12 01:38
"Attempted relative import in non-package" fixing the error please follow the issue https://github.com/instabot-py/instabot.py/issues/886
