### ISSUE TITLE
KeyError: 'edge_media_to_comment'

### ISSUE THREAD

**Issue by juanrojasm** [instabot-py/instabot.py#1880] opened 2019-01-10 23:28 UTC
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

```
Include the contents of the error.log here (if applicable). < REPLACE THIS TEXT
10.01.2019_18:21 Get Media by tag: laminasenresina
10.01.2019_18:21 Removing already liked medias..
Traceback (most recent call last):
  File "contox.py", line 72, in <module>
    bot.new_auto_mod()
  File "C:\Users\Gestor 1\contox\src\instabot.py", line 724, in new_auto_mod
    self.new_auto_mod_comments()
  File "C:\Users\Gestor 1\contox\src\instabot.py", line 792, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['node']['shortcode']) == False:
  File "C:\Users\Gestor 1\contox\src\instabot.py", line 823, in check_exisiting_comment
    comment_list = list(all_data['graphql']['shortcode_media']['edge_media_to_comment']['edges'])
KeyError: 'edge_media_to_comment'
10.01.2019_18:21 Logout: likes - 0, follow - 0, unfollow - 0, comments - 0.
10.01.2019_18:21 Bot work time: 0:01:14.037786
10.01.2019_18:21 Logout success!

## Config

like_per_day=600,
    comments_per_day=100,
    tag_list=['sonrisas' , 'dientesperfectos' , 'dientesblancos' , 'dientessanos' , 'pacientes' , 'colombia' , 'altaesteticadental' , 'excelencia' , 'pasión' , 'odontólogo' , 'saluddental' , 'carillasdentales' , 'esteticadental' , 'diseñodesonrisabogota' , 'odontologiaestetica' , 'atm' , 'turismodental' , 'laminasenresina' , 'veneers' , 'aestheticdentist' , 'estheticdentistry' , 'cosmeticdentistry' , 'dentalcare' , 'odontologiacosmetica' , 'odontologoscolombianos' , 'resinasposteriores' , 'dientesposteriores' , 'incrustacionesdentales' , 'onlay' , 'colegasaprendiendojuntos', 'l:213236545'],
    tag_blacklist=['rain', 'thunderstorm'],
    user_blacklist={},
    max_like_for_one_tag=50,
    follow_per_day=0,
    follow_time=1 * 60,
    unfollow_per_day=0,
    unfollow_break_min=15,
    unfollow_break_max=30,
    log_mod=0,
    proxy='',
    # List of list of words, each of which will be used to generate comment
    # For example: "This shot feels wow!"
    comment_list=[["Ya viste" , "Ya conoces" , "Visitaste"],
                  ["nuestro", "CONTOX en nuestro", "el"],
                  ["sitio web?,", "portal web?,", "portal?,"],
                  ["Adquiere", "Compra", "Conoce", "No te pierdas"],
                  ["tu entrada en", "tu pase en", "las conferencias en", "los talleres en"],
                  ["www.contoxcolombia.com", "contoxcolombia.com", "www.contoxcolombia.com 👩🏼‍🎓👨🏻‍🎓", "contoxcolombia.com 👩🏻‍⚕️👨🏽‍⚕️"]],
    # Use unwanted_username_list to block usernames containing a string
    ## Will do partial matches; i.e. 'mozart' will block 'legend_mozart'
    ### 'free_followers' will be blocked because it contains 'free'
    unwanted_username_list=[
        'second', 'stuff', 'art', 'project', 'love', 'life', 'food', 'blog',
        'free', 'keren', 'photo', 'graphy', 'indo', 'travel', 'art', 'shop',
        'store', 'sex', 'toko', 'jual', 'online', 'murah', 'jam', 'kaos',
        'case', 'baju', 'fashion', 'corp', 'tas', 'butik', 'grosir', 'karpet',
        'sosis', 'salon', 'skin', 'care', 'cloth', 'tech', 'rental', 'kamera',
        'beauty', 'express', 'kredit', 'collection', 'impor', 'preloved',
        'follow', 'follower', 'gain', '.id', '_id', 'bags'
    ],
    unfollow_whitelist=['airbnb'])
while True:

    #print("# MODE 0 = ORIGINAL MODE BY LEVPASHA")
    #print("## MODE 1 = MODIFIED MODE BY KEMONG")
    #print("### MODE 2 = ORIGINAL MODE + UNFOLLOW WHO DON'T FOLLOW BACK")
    #print("#### MODE 3 = MODIFIED MODE : UNFOLLOW USERS WHO DON'T FOLLOW YOU BASED ON RECENT FEED")
    #print("##### MODE 4 = MODIFIED MODE : FOLLOW USERS BASED ON RECENT FEED ONLY")
    #print("###### MODE 5 = MODIFIED MODE : JUST UNFOLLOW EVERYBODY, EITHER YOUR FOLLOWER OR NOT")

    ################################
    ##  WARNING   ###
    ################################

    # DON'T USE MODE 5 FOR A LONG PERIOD. YOU RISK YOUR ACCOUNT FROM GETTING BANNED
    ## USE MODE 5 IN BURST MODE, USE IT TO UNFOLLOW PEOPLE AS MANY AS YOU WANT IN SHORT TIME PERIOD

    mode = 0

    #print("You choose mode : %i" %(mode))
    #print("CTRL + C to cancel this operation or wait 30 seconds to start")
    #time.sleep(30)

    if mode == 0:
        bot.new_auto_mod()

    elif mode == 1:
        check_status(bot)
        while bot.self_following - bot.self_follower > 200:
            unfollow_protocol(bot)
            time.sleep(10 * 60)
            check_status(bot)
        while bot.self_following - bot.self_follower < 400:
            while len(bot.user_info_list) < 50:
                feed_scanner(bot)
                time.sleep(5 * 60)
                follow_protocol(bot)
                time.sleep(10 * 60)
                check_status(bot)

    elif mode == 2:
        bot.bot_mode = 1
        bot.new_auto_mod()

    elif mode == 3:
        unfollow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 4:
        feed_scanner(bot)
        time.sleep(60)
        follow_protocol(bot)
        time.sleep(10 * 60)

    elif mode == 5:
        bot.bot_mode = 2
        unfollow_protocol(bot)

    else:
        print("Wrong mode!")

**Comment by gemoritzt** [comment] 2019-01-11 11:33
Same here since today.

**Comment by dimisdas** [comment] 2019-01-11 11:36
Does this happen on every run or sporadically?

**Comment by gemoritzt** [comment] 2019-01-11 11:37
On every run even on the latest version.

**Comment by dimisdas** [comment] 2019-01-11 11:50
Yup. It used to get the info from https://www.instagram.com/p/%postid%/?__a=1 but it looks like Instagram shut it down. Let me see what I can do.

**Comment by dimisdas** [comment] 2019-01-11 12:17
Made a commit, please download latest version and see if it works.

**Comment by dimisdas** [comment] 2019-01-11 12:39
Could you add those lines after 1056 and post the output?

print(re.search('window._sharedData = (.*?);</script>', r.text, re.DOTALL).group(1))
exit()

![Example](https://dalloway.gr/preview/screenshot.jpg)

**Comment by dimisdas** [comment] 2019-01-11 12:42
Could you change the function like this:

```
 def check_exisiting_comment(self, media_code):
        url_check = self.url_media % (media_code)
        check_comment = self.s.get(url_check)
        if check_comment.status_code == 200:
            all_data = json.loads(re.search('window._sharedData = (.*?);', check_comment.text, re.DOTALL).group(1))['entry_data']['PostPage'][0] #window._sharedData = (.*?);
            
            print(re.search('window._sharedData = (.*?);</script>', r.text, re.DOTALL).group(1))
			exit()
            

```
and post the output.

![Example](https://dalloway.gr/preview/screenshot2.jpg)

**Comment by gemoritzt** [comment] 2019-01-11 12:58
After I did what you wrote I'm getting this. The error is a bit different now:

Traceback (most recent call last):
  File "/Users/moritz/Documents/instabot-2.py-master/example ohne orte_2.py", line 67, in <module>
    bot.new_auto_mod()
  File "/Users/moritz/Documents/instabot-2.py-master/src/instabot.py", line 871, in new_auto_mod
    self.new_auto_mod_comments()    
  File "/Users/moritz/Documents/instabot-2.py-master/src/instabot.py", line 973, in new_auto_mod_comments
    and self.check_exisiting_comment(self.media_by_tag[0]['node']['shortcode']) == False:
  File "/Users/moritz/Documents/instabot-2.py-master/src/instabot.py", line 1000, in check_exisiting_comment
    print(re.search('window._sharedData = (.*?);</script>', r.text, re.DOTALL).group(1))
NameError: name 'r' is not defined
11.01.2019_13:54 Logout: likes - 1, follow - 0, unfollow - 0, comments - 0.
11.01.2019_13:54 Bot work time: 0:00:11.350377
11.01.2019_13:54 Logout success!

**Comment by dimisdas** [comment] 2019-01-11 13:01
sorry it should be the following, 
```
            print(re.search('window._sharedData = (.*?);', check_comment.text, re.DOTALL).group(1))
            exit()
```

My mistake.

**Comment by gemoritzt** [comment] 2019-01-11 13:43
After changing Line 1000 I'm getting a huge Error-Code starting with: 
"{"config":{"csrf_token":"PcX7Vk3UlvEYKr1OPW7PxgMQLvFR3oKR","viewer":{"allow_contacts_sync":true,"biography": ..."
containing my hashtags, biography etc.
Don't know if I should post the whole thing here.

**Comment by dimisdas** [comment] 2019-01-11 13:48
The problem is your data structure is different than mine, for some reason. Instagram might have a beta feature running on your account.

If you feel comfortable enough, you could email them at me@dimis.me and I'll have a quick look

**Comment by Nadastique** [comment] 2019-01-11 13:59
same problem

**Comment by dimisdas** [comment] 2019-01-11 14:06
Please download with latest commit and try again. See if it's fixed now. Thank you!

**Comment by gemoritzt** [comment] 2019-01-11 14:08
It's working! Thank you!!

**Comment by dimisdas** [comment] 2019-01-11 14:09
Cheers!

**Closed by dimisdas** 2019-01-11 14:09 UTC
