### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by JackBone** [instabot-py/instabot.py#1221] opened 2018-04-19 17:50 UTC
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [ ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] If so; have you tried running the code on your local machine?

#### Select one:
- [x ] Bug
- [ ] Feature Request
- [x ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC Linux

## Python Version?
2 / 3

## Description

Type the description of your issue here.
 
today started to log this message : "ValueError: No JSON object could be decoded" there is a fix already on ?
Include the contents of the error.log here (if applicable).
```

**Comment by ChipWolf** [comment] 2018-04-26 08:34
Duplicate of #1153

**Closed by ChipWolf** 2018-04-26 08:34 UTC
