### ISSUE TITLE
ImportError: No module named fake_useragent

### ISSUE THREAD

**Issue by dthurler** [instabot-py/instabot.py#968] opened 2018-02-06 18:28 UTC
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x] I have searched for other issues with the same problem.

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x] If so; have you tried running the code on your local machine?

#### Select one:
- [ ] Bug
- [ ] Feature Request
- [x] Technical Help
- [ ] Other

### Operating System? (include version)
MAC OS High Sierra 10.13.4

## Python Version?
3

## Description

When trying to run the bot, the following error appears.

```
MacBook-Pro-de-Dan:instabot.py-master danmartins$ python example.py
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "/Users/danmartins/Desktop/instabot.py-master/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/Users/danmartins/Desktop/instabot.py-master/src/instabot.py", line 22, in <module>
    from fake_useragent import UserAgent
ImportError: No module named fake_useragent
```

**Comment by oleharland** [comment] 2018-02-07 12:36
You have to do this
`sudo pip install fake-useragent`

see step 7 on this article https://medium.com/@rohanarun/how-to-build-an-instagram-bot-farm-in-15-minutes-for-free-14468c844f7a

**Comment by dthurler** [comment] 2018-02-07 13:02
I’ve already done that, but still does not work :(



________________________________________________________________________________
(PT) Esta mensagem pode conter informação confidencial ou privilegiada, sendo seu sigilo protegido por lei. Se você não for o destinatário ou a pessoa autorizada a receber esta mensagem, não pode usar, copiar ou divulgar as informações nela contidas ou tomar qualquer ação baseada nessas informações. Se você recebeu esta mensagem por engano, por favor, avise imediatamente ao remetente, respondendo o e-mail e em seguida apague-a. Agradecemos sua cooperação.

(EN) This message may contain confidential or privileged information and its confidentiality is protected by law. If you are not the addressed or authorized person to receive this message, you must not use, copy, disclose or take any action based on it or any information herein. If you have received this message by mistake, please advise the sender immediately by replying the e-mail and then deleting it. Thank you for your cooperation.

**Comment by ri7nz** [comment] 2018-02-08 11:49
use this command @dthurler 
```sh
pip install fake_useragent --user
```

**Comment by NandoPrates** [comment] 2018-02-08 17:09
Try pip2 install fake_useragent

**Comment by bahadorq** [comment] 2018-02-15 22:26
@ri7nz 
"pip install fake_useragent --user"
solved my problem but now i get this:
"fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached"

**Comment by viniciusams** [comment] 2018-02-18 16:15
I'm facing this problem too
"fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached"

**Comment by ri7nz** [comment] 2018-02-19 10:11
@viniciusams  @bahadorq  what your python version used ?

**Comment by bahadorq** [comment] 2018-02-19 10:19
I dont know the version, Im using pythonanywhere.com 






On Mon, Feb 19, 2018 at 1:41 PM +0330, "ri7nz" <notifications@github.com> wrote:












@viniciusams  @bahadorq  what your python version used ?

**Comment by ri7nz** [comment] 2018-02-19 10:30
@bahadorq okay

you can edit src/instabot.py line 163 , like this my pull request 
https://github.com/instabot-py/instabot.py/pull/981/files#diff-91adcadbdf4fad3eb76d66f30bfba3afR163

**Comment by bahadorq** [comment] 2018-02-19 13:59
@ri7nz i edited src/instabot.py like you said but i still get that error
this is the whole thing:
Traceback (most recent call last):
  File "/home/bahadorq/instabot.py/example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/home/bahadorq/instabot.py/src/instabot.py", line 162, in __init__
    fake_ua = UserAgent(verify_ssl=False)
  File "/home/bahadorq/.local/lib/python2.7/site-packages/fake_useragent/fake.py", line 69, in __init__
    self.load()
  File "/home/bahadorq/.local/lib/python2.7/site-packages/fake_useragent/fake.py", line 78, in load
    verify_ssl=self.verify_ssl,
  File "/home/bahadorq/.local/lib/python2.7/site-packages/fake_useragent/utils.py", line 250, in load_cached
    update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
  File "/home/bahadorq/.local/lib/python2.7/site-packages/fake_useragent/utils.py", line 245, in update
    write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
  File "/home/bahadorq/.local/lib/python2.7/site-packages/fake_useragent/utils.py", line 189, in load
    verify_ssl=verify_ssl,
  File "/home/bahadorq/.local/lib/python2.7/site-packages/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
>>>

**Comment by ChipWolf** [comment] 2018-04-03 16:44
If this is still an issue, please open a new issue. Thanks!

**Comment by herwincamargo** [comment] 2018-04-13 02:41
I'm having the same issue!

**Comment by ChipWolf** [comment] 2018-04-15 09:50
There are two different issues here.

One is people not installing the correct python 3 dependencies.
These are the commands to fix that and run the bot:
```
python3 -m pip install -r requirements.txt --upgrade
python3 example.py
```

The other issue is a duplicate of #1162, so I'm calling this the dupe and redirecting people there

**Comment by ChipWolf** [comment] 2018-04-15 09:50
Duplicate of #1162

**Closed by ChipWolf** 2018-04-15 09:50 UTC
