### ISSUE TITLE
log in error or challenge required 

### ISSUE THREAD

**Issue by darkroker** [instabot-py/instabot.py#1861] opened 2018-12-31 12:24 UTC
}
-->

Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [X] If so; have you tried running the code on your local machine?

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
- [ ] MAC
- [x] Windows
- [ ] Linux
- [ ] Android

## Python Version?
- [ ] 2.x
- [x] 3.x

## Description of your issue

```
I can not log in... error connection i did everything your guys say but i can not log in again
 and i try something different the challenge required just show the link and send me back to start 
![maxthonsnap20181231081414](https://user-images.githubusercontent.com/46049466/50560250-3b104480-0cd5-11e9-9cda-29d417bec739.jpg)
![error 2](https://user-images.githubusercontent.com/46049466/50560274-7a3e9580-0cd5-11e9-986f-2477e020dac4.jpg)

 
```

## Config

```

```

**Comment by psannino77** [comment] 2019-01-02 14:37
Some issue, I have Challenge Required error :(

**Comment by DrCigar** [comment] 2019-01-02 21:17
Hello @dabsx , I tried the above process and entered the code delivered to my mobile, but I still get the same error message in terminal on Mac, same error that @darkroker has reported.   I can confirm I have the most recent instaloader, pip, and python all running.

**Comment by Mehranp** [comment] 2019-01-03 08:42
same

**Comment by pablo3600** [comment] 2019-01-03 11:12
better take and do it yourself because for the results that will give you the bot that continually throws errors lose time and the same would have gotten yourself doing your follow unfollow with your finger the bot is a crap if not with time you will give me the reason over normalmene the people who follow the basis of hagstags are users to make bulk as they neither interact with your content or are from countries that the same for the purpose you want do not serve you more than to fatten your list of followers, over there are people that is so stupid that they will just accept the request and it does not start to follow you

**Comment by manguszta** [comment] 2019-01-04 09:33
4 of my 5 accounts are working, 1 keeps refusing connection. They are all using the same instabot, instaloader applied. Sometimes I need to use my mobile internet or my workplace wifi to login to one or two accounts.

**Comment by Massimosso** [comment] 2019-01-04 14:06
@manguszta do u use a terminal or a Vps server online?

I use a Vps on Ubuntu so I can’t change my internet connection or my ip address

**Comment by Massimosso** [comment] 2019-01-04 15:31
@dabsx continue to not works.. after all installations the command `py -3 example.py` not exists
Do u have any news?

**Comment by Massimosso** [comment] 2019-01-04 15:33
@dabsx continue to not works.. after all installations the command `py -3 example.py` not exists, but I can start the bot only by the command `python3 example.py` but in this way the system continue to ask me the challenge required... I've all the most recent instaloader, pip, and python all running.

Do u have any news?

**Comment by DrCigar** [comment] 2019-01-04 17:10
Mine started working today again on a new account and also on both old accounts.  However, when logged out, challenge request showed up again on one when trying to log back in.

I think it resets every now and again and we can re-login without the challenge but unsure how to get any consistency with this bot.  I also show that Instabot update is available in terminal but am not sure how through terminal to update this bot.  Does anyone know that script?

**Comment by dabsx** [comment] 2019-01-05 06:36
> @manguszta do u use a terminal or a Vps server online?
> 
> I use a Vps on Ubuntu so I can’t change my internet connection or my ip address

I use local command prompt on windows.

**Comment by dabsx** [comment] 2019-01-05 06:46
ok guys so mine stopped again and I tried a few new steps that fixed the error:

1. Start by following the steps above and try to login, If the error persists then follow steps 2 onwards : [1861](https://github.com/instabot-py/instabot.py/issues/1861#issuecomment-450829896)

2. Delete the fake-useragent.json file in temporary folder
Location: C:\Users\--YOUR_USERNAME--\AppData\Local\Temp

3. Delete the contents of `__pycache__` folder located inside of `src` folder

4. Run the bot using: `py -3 example.py`

**Comment by darkroker** [comment] 2019-01-05 12:32
first how upgrade instaloader  i just did that step send me error, them i dont do that continued do the others steps and gimme this 
![maxthonsnap20190105083040](https://user-images.githubusercontent.com/46049466/50724477-72f7fd00-10c4-11e9-92f0-0faa142a487d.jpg)

**Comment by Massimosso** [comment] 2019-01-05 20:58
@DrCigar can u send us ur package files? Please 🙏🏻

**Comment by darkroker** [comment] 2019-01-06 14:57
hey guys this worked for me. 

1) downloaded it from this: https://github.com/instabot-py/instabot.py.git

2) I pasted it my old file file username.py and my old follows_db and tried to log in, I failed. sent me a error not like 403.  then I do this https://github.com/instabot-py/instabot.py/pull/1788. for now it´s working ! :D

**Comment by 1nv4510n** [comment] 2019-01-06 18:10
@darkroker can u share ur instabot folder?

**Comment by jinnishdalal** [comment] 2019-01-09 17:13
> }
> -->
> 
> Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
> 
> * [x]  I have searched for other issues with the same problem. (including #1153)
> 
> ## Hosting
> * [ ]  Are you hosting the bot on a VPS or other Cloud hosting?
> * [x]  If so; have you tried running the code on your local machine?
> 
> #### Select one:
> * [x]  Bug
> * [ ]  Feature Request
> * [ ]  Technical Help
> * [ ]  Other
> 
> ### Operating System? (include version)
> * [ ]  MAC
> * [x]  Windows
> * [ ]  Linux
> * [ ]  Android
> 
> ## Python Version?
> * [ ]  2.x
> * [x]  3.x
> 
> ## Description of your issue
> ```
> I can not log in... error connection i did everything your guys say but i can not log in again
>  and i try something different the challenge required just show the link and send me back to start 
> ![maxthonsnap20181231081414](https://user-images.githubusercontent.com/46049466/50560250-3b104480-0cd5-11e9-9cda-29d417bec739.jpg)
> ![error 2](https://user-images.githubusercontent.com/46049466/50560274-7a3e9580-0cd5-11e9-986f-2477e020dac4.jpg)
> 
>  
> ```
> ## Config
> ```
> 
> ```
Hello,
The issue is not with the bot but instagram is blocking the login as it notices a login from a suspicious device .
Solution->
Open instagram.com on a web browser , login into the account . you will get a popup stating that a strange login was noticed which was blocked . so all you have to do is click it was me . DONE!!
"IT WORKED FOR ME ."

**Comment by itsmejamie** [comment] 2019-01-09 20:08
Previously had the issue with challenge required, eventually the bot ran without being challenged so had the bot run for almost 1 week solid. Tried to reset the bot and now I'm getting the challenge. 

No code is being sent. I have tried removing and adding my phone number again. But no luck. Have tried logging out of instagram on a web browser and logging back in and I don't get asked 'was this you?" I am being sent "we noticed a new log in", but only from the actual browsers I am using. 

Have tried using two different internet connections, and also two different computers. But no luck.

**Comment by pierresauvignon** [comment] 2019-01-09 22:37
Same here, running the brand new version (v1.2.0/3) untouched and getting prompted to go to the URL for the challenge request. However all I get is a "Page not found" error on instagram.

> Error
This page could not be loaded. If you have cookies disabled in your browser, or you are browsing in Private Mode, please try enabling cookies or turning off Private Mode, and then retrying your action.

And no code is sent to either my email or phone. I'm not getting any of the "was this you" type of alerts either.

**Comment by Massimosso** [comment] 2019-01-10 11:36
@fibercoolb do u use an vps server or ur terminal computer?

**Comment by fibercool** [comment] 2019-01-10 11:41
@Massimosso i'm running on an VPS (AWS).

i changed this line 110: 

user_agent = "Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko"

**Comment by Massimosso** [comment] 2019-01-10 12:05
@fibercool try to use different user agents that you find online on your vps. Before I found mine I had to try 5/6 differents 😅

**Comment by fibercool** [comment] 2019-01-10 13:49
@Massimosso thanks for you answer.

I already tried to change my line 216 to:

**Comment by itsmejamie** [comment] 2019-01-10 16:32
@Massimosso 

> @itsmejamie do u use an vps server or the terminal of the computer?

 I'm using IDLE for Mac
> 
> Have u changed the user_agent in instabot.py?

Similar to the other comments I have tried it, but can't seem to get the correct format. Mine is showing as 

"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.2 Safari/605.1.15"

**Comment by itsmejamie** [comment] 2019-01-10 17:17
I'm now able to get it to work. I'm using the line

self.user_agent = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.2 Safari/605.1.15")

**Comment by spaarkly** [comment] 2019-01-11 01:11
All fixes and updates work for a couple days max, up to a week if you're lucky.

**Comment by murlikanne** [comment] 2019-01-11 09:16
I have this error on 3 accounts, two accounts seem to be working fine after I input the Verification ID received on mail. Old accounts seems to be having a problem. Help is appreciated.

**Comment by murlikanne** [comment] 2019-01-11 09:16
> Hey everyone, if you are facing the "Challenge Required" problem, please try the following:
> 
> 1. Download a fresh copy of the bot from here: https://github.com/dimisdas/instabot.py
> 2. Configure the Example.py file as per your taste.
> 3. Open a command prompt in the folder where your bot is installed and run the following command without the double quotes:
>    `pip3 install --upgrade git+https://github.com/instaloader/instaloader`
> 4. Now run your bot using the following command in the same command prompt window without the double quotes:
>    `py -3 example.py`
> 5. Let me know if it bypasses the "Challenge Required" error.

"Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/instaloader/instaloader C:\Users\DELL\AppData\Local\Temp\pip-req-build-gb_umf20
Cannot find command 'git' - do you have 'git' installed and in your PATH?"

This is the error I see when I try to upgrade Git, help!!

**Comment by spaarkly** [comment] 2019-01-11 12:32
I think I found the fix. The challenge and the verification code loop is triggered on your main network. It's not a bot problem. 100% working way is to use the 4g on your phone, hotspot the network, then run the terminal on your PC connected to the 4g.
You can switch back to wifi and turn off the 4g right after getting logged in. There will be no challenge nor an error. Good luck.

**Comment by fibercool** [comment] 2019-01-11 13:23
> I think I found the fix. The challenge and the verification code loop is triggered on your main network. It's not a bot problem. 100% working way is to use the 4g on your phone, hotspot the network, then run the terminal on your PC connected to the 4g.
> You can switch back to wifi and turn off the 4g right after getting logged in. There will be no challenge nor an error. Good luck.

Thanks but thats a workaround only in cases you are executing the bot locally, it does not fix if you cant hotspot the network to the terminal.

**Comment by dimisdas** [comment] 2019-01-12 01:59
The session_persist branch now supports persistent sessions.
https://github.com/instabot-py/instabot.py/tree/session_persist

You'll have to manually enter a session file name when calling the class (**session_file** option), or use run.py. This should help reduce drastically the amount of relogins made by the bot.

**Comment by DarkSuniuM** [comment] 2019-01-12 15:35
Try the new version and reply my comment if u still got the problem, Im closing this issue for now

**Closed by DarkSuniuM** 2019-01-12 15:35 UTC
Labels: status/fixed

**Comment by hemant2410** [comment] 2019-11-08 03:14
*******error what i get********

python3 example.py                                  INFO:instabot_py.config:Setting configuration from instabot.config.yml : OK
Traceback (most recent call last):                      File "/data/data/com.termux/files/usr/lib/python3.7/logging/config.py", line 384, in resolve
    found = self.importer(used)                       ModuleNotFoundError: No module named 'telegram_handler'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.7/logging/config.py", line 563, in configure                handler = self.configure_handler(handlers[name])
  File "/data/data/com.termux/files/usr/lib/python3.7/logging/config.py", line 713, in configure_handler        klass = self.resolve(cname)
  File "/data/data/com.termux/files/usr/lib/python3.7/logging/config.py", line 397, in resolve                  raise v
  File "/data/data/com.termux/files/usr/lib/python3.7/logging/config.py", line 384, in resolve                  found = self.importer(used)
ValueError: Cannot resolve 'telegram_handler.TelegramHandler': No module named 'telegram_handler'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "example.py", line 4, in <module>
    from instabot_py import InstaBot
  File "/data/data/com.termux/files/home/instabot.py/instabot_py/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/data/data/com.termux/files/home/instabot.py/instabot_py/instabot.py", line 22, in <module>
    from instabot_py.config import config
  File "/data/data/com.termux/files/home/instabot.py/instabot_py/config.py", line 43, in <module>
    logging.config.dictConfig(config.get("logging"))
  File "/data/data/com.termux/files/usr/lib/python3.7/logging/config.py", line 800, in dictConfig
    dictConfigClass(config).configure()
  File "/data/data/com.termux/files/usr/lib/python3.7/logging/config.py", line 571, in configure
    '%r' % name) from e
ValueError: Unable to configure handler 'telegram'
$
