### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by KevinMaldjian** [instabot-py/instabot.py#1200] opened 2018-04-16 03:44 UTC
Hey,

Having trouble running this in python 3 putting the code in below.

```
def auto_unfollow(self):
        checking = True
        while checking:
            username_row = get_username_random(self)
            if not username_row:
                self.write_log("Looks like there is nobody to unfollow.")
                return False
            current_id = username_row[0]
            current_user = username_row[1]
            unfollow_count = username_row[2]

            if not current_user:
                current_user = self.get_username_by_user_id(user_id=current_id)
            if not current_user:
                log_string = "api limit reached from instagram. Will try later"
                self.write_log(log_string)
                return False
            for wluser in self.unfollow_whitelist:
                if wluser == current_user:
                    log_string = (
                        "found whitelist user, starting search again")
                    self.write_log(log_string)
                    break
            else:
                checking = False
```

Asking in reference to this similar issue:  ((https://github.com/instabot-py/instabot.py/issues/438))

Receiving this error when I try to run it. Wondering if someone could paste in the correct indentation for the code.

Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/seanmaldjian/Desktop/instabot.py-master/src/instabot.py", line 231, in __init__
    self.login()
  File "/Users/seanmaldjian/Desktop/instabot.py-master/src/instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/Users/seanmaldjian/Desktop/instabot.py-master/src/userinfo.py", line 41, in get_user_id_by_login
    all_data = json.loads(info.text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Seans-MacBook-Pro:instabot.py-master seanmaldjian$ Traceback (most recent call last):
  File "example.py", line 52, in <module>
    unfollow_whitelist=['example_user_1', 'example_user_2'])
  File "/Users/seanmaldjian/Desktop/instabot.py-master/src/instabot.py", line 231, in __init__
    self.login()
  File "/Users/seanmaldjian/Desktop/instabot.py-master/src/instabot.py", line 300, in login
    self.user_id = ui.get_user_id_by_login(self.user_login)
  File "/Users/seanmaldjian/Desktop/instabot.py-master/src/userinfo.py", line 41, in get_user_id_by_login
    all_data = json.loads(info.text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Seans-MacBook-Pro:instabot.py-master seanmaldjian$ 

Thanks,

-Kevin

**Comment by Damny89** [comment] 2018-04-16 05:56
I get this error too!

**Comment by srnka** [comment] 2018-04-16 07:42
same here

**Comment by nivong** [comment] 2018-04-16 08:13
https://github.com/instabot-py/instabot.py/issues/1153

**Comment by ChipWolf** [comment] 2018-04-26 08:35
Duplicate of #1153

**Closed by ChipWolf** 2018-04-26 08:35 UTC
