### ISSUE TITLE
Error? It was working, but now its stoped.

### ISSUE THREAD

**Issue by rodrigozile** [instabot-py/instabot.py#1224] opened 2018-04-21 01:01 UTC
> Fill in all requirements *before* submitting an issue.
> Do not delete any of the template, fill all of it in; even if you think it doesn't apply to your issue.
> If you fail to follow these simple instructions, we will close the ticket.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

- [x ] I have searched for other issues with the same problem. (including #1153)

## Hosting
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [x ] If so; have you tried running the code on your local machine?

#### Select one:
- [x ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
Windows 

## Python Version?
 3

## Description
![image](https://user-images.githubusercontent.com/38574845/39078836-11636872-44e6-11e8-9a24-a3d77e4dae0f.png)

Type the description of your issue here.
https://user-images.githubusercontent.com/38574845/39078836-11636872-44e6-11e8-9a24-a3d77e4dae0f.png
```
Include the contents of the error.log here (if applicable).
```

**Comment by ayush3298** [comment] 2018-04-21 08:27
That is due to.. Instagram had denieded requests to its __a=1 URL.. So we can not have user id of the URL... So if you are working on single insta account.. U can hardcode your inta id... In userinfo.py.. And wait till we find another way to get user id

**Comment by FenniX777** [comment] 2018-04-21 10:12
@ayush3298 when i do that, the bot comments the same picture every time, is it possibly caused by the hardcoded ID?

**Comment by rodrigozile** [comment] 2018-04-21 22:07
Doesnt works too... I dont know what to do.. there is any alternative about instabots??
I loved this one.. =/

**Comment by srwiseman** [comment] 2018-04-22 16:46
Change the files as referenced in my fix #1225

**Comment by FenniX777** [comment] 2018-04-24 05:06
@ayush3298 yes, still same problem even with only one hashtag

**Comment by ChipWolf** [comment] 2018-04-26 08:40
Duplicate of #1153

**Closed by ChipWolf** 2018-04-26 08:40 UTC
